/* PADANG · i18n BIOS · traduções das bios dos artistas no roster
 * Hook via MutationObserver na modal de roster.html — quando abre, traduz a bio
 * automaticamente conforme o idioma ativo. PT é o source (não precisa traduzir).
 * Nomes próprios (Padang Records, releases, festivais) mantidos em forma original.
 */
(function() {
  'use strict';

  const BIOS = {
    "AOOS": {
      en: '"Citizen of the Cosmos". <b>Psychedelic Dark Progressive</b> producer on Padang Records — blends dark, atmospheric and trippy sounds with groovy basslines. Roots in Psytrance, Techno, Breakbeat and Ambient. Released <b>Cosmic Visitors</b> (10/2024) and <b>Spaceman</b> (03/2025); featured on Padang VAs <b>The Nightmare</b> (Funboosting DarkSide), <b>Nyctophilia II</b> (The Pinwheel) and <b>Reborn</b> (Let There Be Dark).',
      es: '"Citizen of the Cosmos". Productor de <b>Psychedelic Dark Progressive</b> en Padang Records — mezcla sonidos oscuros, atmosféricos y trippy con basslines groovy. Raíces en Psytrance, Techno, Breakbeat y Ambient. Lanzó <b>Cosmic Visitors</b> (10/2024) y <b>Spaceman</b> (03/2025); presente en las VAs Padang <b>The Nightmare</b> (Funboosting DarkSide), <b>Nyctophilia II</b> (The Pinwheel) y <b>Reborn</b> (Let There Be Dark).',
      de: '"Citizen of the Cosmos". <b>Psychedelic Dark Progressive</b>-Produzent auf Padang Records — mischt düstere, atmosphärische und trippige Sounds mit grooviger Basslines. Wurzeln in Psytrance, Techno, Breakbeat und Ambient. Veröffentlichte <b>Cosmic Visitors</b> (10/2024) und <b>Spaceman</b> (03/2025); auf den Padang-VAs <b>The Nightmare</b> (Funboosting DarkSide), <b>Nyctophilia II</b> (The Pinwheel) und <b>Reborn</b> (Let There Be Dark).',
      fr: '"Citizen of the Cosmos". Producteur de <b>Psychedelic Dark Progressive</b> sur Padang Records — mêle sons sombres, atmosphériques et trippy avec des basslines groovy. Racines Psytrance, Techno, Breakbeat et Ambient. A sorti <b>Cosmic Visitors</b> (10/2024) et <b>Spaceman</b> (03/2025); présent sur les VAs Padang <b>The Nightmare</b> (Funboosting DarkSide), <b>Nyctophilia II</b> (The Pinwheel) et <b>Reborn</b> (Let There Be Dark).',
      ja: '"Citizen of the Cosmos"。Padang Records 所属の <b>Psychedelic Dark Progressive</b> プロデューサー — ダーク、アトモスフェリック、トリッピーなサウンドをグルーヴィーなベースラインに融合。ルーツは Psytrance、Techno、Breakbeat、Ambient。<b>Cosmic Visitors</b>（2024年10月）と <b>Spaceman</b>（2025年3月）をリリース。Padang VA <b>The Nightmare</b>（Funboosting DarkSide）、<b>Nyctophilia II</b>（The Pinwheel）、<b>Reborn</b>（Let There Be Dark）に参加。'
    },

    "Akudama": {
      en: '<b>James Toa</b>, New Zealand. Immersed in psytech and dark progressive — hypnotic atmospheres and precisely sculpted lows. Part of the Padang Records family. Booking: akudamamusicc@gmail.com.',
      es: '<b>James Toa</b>, Nueva Zelanda. Inmerso en psytech y dark progressive — atmósferas hipnóticas y graves esculpidos con precisión. Forma parte de la familia Padang Records. Booking: akudamamusicc@gmail.com.',
      de: '<b>James Toa</b>, Neuseeland. Eingetaucht in Psytech und Dark Progressive — hypnotische Atmosphären und präzise geformte Bässe. Teil der Padang-Records-Familie. Booking: akudamamusicc@gmail.com.',
      fr: '<b>James Toa</b>, Nouvelle-Zélande. Plongé dans le psytech et le dark progressive — atmosphères hypnotiques et basses sculptées avec précision. Fait partie de la famille Padang Records. Booking : akudamamusicc@gmail.com.',
      ja: '<b>James Toa</b>、ニュージーランド出身。Psytech と Dark Progressive に没入 — 催眠的なアトモスフィアと精密に造形された低音域。Padang Records ファミリーの一員。Booking: akudamamusicc@gmail.com。'
    },

    "Algia": {
      en: '<b>Tóth Bence</b>, Budapest, Hungary. DJ and producer of <b>Dark Progressive and Techno</b> — dense textures, steady pulse. Released <b>Unstable Orbit</b> on Padang Records and headlined <b>Padang Lab Series EP.17</b> (09/10/2025). Contact: algiatek@gmail.com.',
      es: '<b>Tóth Bence</b>, Budapest, Hungría. DJ y productor de <b>Dark Progressive y Techno</b> — texturas densas, pulso firme. Lanzó <b>Unstable Orbit</b> en Padang Records y protagonizó <b>Padang Lab Series EP.17</b> (09/10/2025). Contacto: algiatek@gmail.com.',
      de: '<b>Tóth Bence</b>, Budapest, Ungarn. DJ und Produzent für <b>Dark Progressive und Techno</b> — dichte Texturen, stetiger Puls. Veröffentlichte <b>Unstable Orbit</b> auf Padang Records und stand im Mittelpunkt der <b>Padang Lab Series EP.17</b> (09.10.2025). Kontakt: algiatek@gmail.com.',
      fr: '<b>Tóth Bence</b>, Budapest, Hongrie. DJ et producteur de <b>Dark Progressive et Techno</b> — textures denses, pulsation ferme. A sorti <b>Unstable Orbit</b> sur Padang Records et a porté la <b>Padang Lab Series EP.17</b> (09/10/2025). Contact : algiatek@gmail.com.',
      ja: '<b>Tóth Bence</b>、ハンガリー・ブダペスト出身。<b>Dark Progressive と Techno</b> の DJ／プロデューサー — 濃密なテクスチャと安定したパルス。Padang Records から <b>Unstable Orbit</b> をリリースし、<b>Padang Lab Series EP.17</b>（2025年10月9日）の中心を担う。連絡先: algiatek@gmail.com。'
    },

    "Alternative Roots": {
      en: '<b>Ricardo</b>, Sesimbra, Portugal. Discovered psychedelic music in the dark valleys of Portugal and dove into the scene to the point of organising his own parties and DJing. Production features heavy driving beats and deep basslines punctuated by dark atmospheres that transport the listener to unknown dimensions. On Padang Records: <b>Mind Control</b> with Champirolls (10/2024).',
      es: '<b>Ricardo</b>, Sesimbra, Portugal. Descubrió la música psicodélica en los valles oscuros de Portugal y se sumergió en la escena al punto de organizar sus propias fiestas y hacer DJing. Producción con beats pesados y basslines profundos, puntuados por atmósferas oscuras que transportan al oyente a dimensiones desconocidas. En Padang Records: <b>Mind Control</b> con Champirolls (10/2024).',
      de: '<b>Ricardo</b>, Sesimbra, Portugal. Entdeckte psychedelische Musik in den dunklen Tälern Portugals und tauchte so tief in die Szene ein, dass er eigene Partys organisierte und auflegte. Produktion mit treibenden Beats und tiefen Basslines, durchsetzt von düsteren Atmosphären, die in unbekannte Dimensionen führen. Auf Padang Records: <b>Mind Control</b> mit Champirolls (10/2024).',
      fr: '<b>Ricardo</b>, Sesimbra, Portugal. Découvrit la musique psychédélique dans les vallées sombres du Portugal et plongea dans la scène au point d\'organiser ses propres soirées et de mixer. Production faite de beats pesants et de basslines profondes, ponctués d\'atmosphères sombres qui transportent l\'auditeur vers des dimensions inconnues. Sur Padang Records : <b>Mind Control</b> avec Champirolls (10/2024).',
      ja: '<b>Ricardo</b>、ポルトガル・セジンブラ出身。ポルトガルの暗い谷でサイケデリック音楽と出会い、シーンに深く飛び込み、自身のパーティを主催して DJ を始めた。重く突き進むビートと深いベースライン、未知の次元へリスナーを誘うダークなアトモスフィアが特徴の制作。Padang Records から：Champirolls との <b>Mind Control</b>（2024年10月）。'
    },

    "Anadrome": {
      en: '<b>Connor McLean</b>, Central Coast, Australia — <b>Spinal Collective</b> crew. Under the motto "Sounds of a madman", he delivers gritty psychedelia with edge and organic shake. Debut EP <b>Self Inflicted</b> on Padang Records (18/02/2026) — three tracks (Hollow, Ensnared, System Diagnostics) distilling his dark aesthetic.',
      es: '<b>Connor McLean</b>, Central Coast, Australia — colectivo <b>Spinal Collective</b>. Bajo el lema "Sounds of a madman", entrega psicodelia áspera con filo y vibración orgánica. EP debut <b>Self Inflicted</b> en Padang Records (18/02/2026) — tres tracks (Hollow, Ensnared, System Diagnostics) que destilan su estética oscura.',
      de: '<b>Connor McLean</b>, Central Coast, Australien — Kollektiv <b>Spinal Collective</b>. Unter dem Motto "Sounds of a madman" liefert er rauhe Psychedelia mit Kante und organischer Schwingung. Debüt-EP <b>Self Inflicted</b> auf Padang Records (18.02.2026) — drei Tracks (Hollow, Ensnared, System Diagnostics), die seine düstere Ästhetik destillieren.',
      fr: '<b>Connor McLean</b>, Central Coast, Australie — collectif <b>Spinal Collective</b>. Sous la devise "Sounds of a madman", il livre une psychédélie râpeuse au tranchant organique. EP de début <b>Self Inflicted</b> sur Padang Records (18/02/2026) — trois morceaux (Hollow, Ensnared, System Diagnostics) qui distillent son esthétique sombre.',
      ja: '<b>Connor McLean</b>、オーストラリア・セントラルコースト出身 — コレクティブ <b>Spinal Collective</b> 所属。「Sounds of a madman」というモットーのもと、エッジとオーガニックな振動を持つザラついたサイケデリアを届ける。Padang Records からデビュー EP <b>Self Inflicted</b>（2026年2月18日） — 3 トラック（Hollow、Ensnared、System Diagnostics）が彼のダークな美学を凝縮。'
    },

    "Anaïs Lin": {
      en: 'A presence in the Portuguese underground since 2012. <b>Festivals:</b> <b>Burning Man</b>, <b>Modem Festival</b> (Croatia), <b>Boom Festival</b> (Portugal), <b>Esoteric Festival</b>, Fora de Tempo Festival, GemFest. Signed to Padang Records in 2018 and curated <b>TechnoMad</b> (the label\'s most successful compilation) and <b>Padang Lab Series EP.11</b>. Maintains experimental alter-ego Inthelinbo.',
      es: 'Presencia en la escena underground portuguesa desde 2012. <b>Festivales:</b> <b>Burning Man</b>, <b>Modem Festival</b> (Croacia), <b>Boom Festival</b> (Portugal), <b>Esoteric Festival</b>, Fora de Tempo Festival, GemFest. Firmó con Padang Records en 2018 y curó <b>TechnoMad</b> (la compilación más exitosa del sello) y <b>Padang Lab Series EP.11</b>. Mantiene alter-ego experimental Inthelinbo.',
      de: 'Seit 2012 eine Größe in der portugiesischen Underground-Szene. <b>Festivals:</b> <b>Burning Man</b>, <b>Modem Festival</b> (Kroatien), <b>Boom Festival</b> (Portugal), <b>Esoteric Festival</b>, Fora de Tempo Festival, GemFest. 2018 bei Padang Records unter Vertrag, kuratierte sie <b>TechnoMad</b> (die erfolgreichste Compilation des Labels) und <b>Padang Lab Series EP.11</b>. Pflegt das experimentelle Alter-Ego Inthelinbo.',
      fr: 'Une figure de la scène underground portugaise depuis 2012. <b>Festivals :</b> <b>Burning Man</b>, <b>Modem Festival</b> (Croatie), <b>Boom Festival</b> (Portugal), <b>Esoteric Festival</b>, Fora de Tempo Festival, GemFest. Signée chez Padang Records en 2018, elle a curaté <b>TechnoMad</b> (la compilation la plus aboutie du label) et <b>Padang Lab Series EP.11</b>. Maintient l\'alter-ego expérimental Inthelinbo.',
      ja: '2012年からポルトガル・アンダーグラウンドシーンの中核。<b>フェス：</b><b>Burning Man</b>、<b>Modem Festival</b>（クロアチア）、<b>Boom Festival</b>（ポルトガル）、<b>Esoteric Festival</b>、Fora de Tempo Festival、GemFest。2018年に Padang Records と契約し、<b>TechnoMad</b>（レーベル屈指の成功を収めたコンピレーション）と <b>Padang Lab Series EP.11</b> をキュレーション。実験的な別名義 Inthelinbo も継続。'
    },

    "Backendorf": {
      en: '<b>Camila Backendorf</b>, DJ/producer from Porto Alegre. Part of the Padang Records family, she navigates psytech and dark progressive with clinical sound design and a selection tuned to the dancefloor\\\'s nuances.',
      es: '<b>Camila Backendorf</b>, DJ/productora de Porto Alegre. Forma parte de la familia Padang Records, navegando entre psytech y dark progressive con diseño sonoro clínico y selección atenta a los matices del dancefloor.',
      de: '<b>Camila Backendorf</b>, DJ/Produzentin aus Porto Alegre. Teil der Padang-Records-Familie, bewegt sie sich zwischen Psytech und Dark Progressive mit klinischem Sound-Design und einer Auswahl, die auf die Nuancen des Dancefloors abgestimmt ist.',
      fr: '<b>Camila Backendorf</b>, DJ/productrice de Porto Alegre. Membre de la famille Padang Records, elle navigue entre psytech et dark progressive avec un sound design clinique et une sélection attentive aux nuances du dancefloor.',
      ja: '<b>Camila Backendorf</b>、ブラジル・ポルト・アレグレ出身の DJ／プロデューサー。Padang Records ファミリーの一員として、クリニカルなサウンド・デザインとダンスフロアのニュアンスに敏感なセレクションで、Psytech と Dark Progressive の間を巡る。'
    },

    "Bensaid": {
      en: '<b>Benjamin Garrido</b>, Chilean producer based in Germany. Released <b>Virtuous Spiral</b> on Padang Records (07/2023) and contributed to label compilations with the <b>Slippery Slope</b> remix (Akari System) and tracks <b>Onduwave</b> (VA Exogenesis) and <b>Hit for The Hater</b> (Technomad II) — always faithful to the dark progressive language that defines him.',
      es: '<b>Benjamin Garrido</b>, productor chileno radicado en Alemania. Lanzó <b>Virtuous Spiral</b> en Padang Records (07/2023) y participó en compilaciones del sello con el remix <b>Slippery Slope</b> (Akari System) y los tracks <b>Onduwave</b> (VA Exogenesis) y <b>Hit for The Hater</b> (Technomad II) — siempre fiel al recorte progressive oscuro que define su lenguaje.',
      de: '<b>Benjamin Garrido</b>, chilenischer Produzent mit Sitz in Deutschland. Veröffentlichte <b>Virtuous Spiral</b> auf Padang Records (07/2023) und steuerte zu Label-Compilations den Remix <b>Slippery Slope</b> (Akari System) sowie die Tracks <b>Onduwave</b> (VA Exogenesis) und <b>Hit for The Hater</b> (Technomad II) bei — stets treu der dunklen progressiven Sprache, die ihn ausmacht.',
      fr: '<b>Benjamin Garrido</b>, producteur chilien basé en Allemagne. A sorti <b>Virtuous Spiral</b> sur Padang Records (07/2023) et nourri les compilations du label avec le remix <b>Slippery Slope</b> (Akari System) et les morceaux <b>Onduwave</b> (VA Exogenesis) et <b>Hit for The Hater</b> (Technomad II) — fidèle à la langue dark progressive qui le définit.',
      ja: '<b>Benjamin Garrido</b>、ドイツ在住のチリ人プロデューサー。Padang Records から <b>Virtuous Spiral</b>（2023年7月）をリリースし、レーベルのコンピレーションに <b>Slippery Slope</b>（Akari System）リミックスと、<b>Onduwave</b>（VA Exogenesis）、<b>Hit for The Hater</b>（Technomad II）の楽曲で参加 — 彼を定義するダーク・プログレッシブの言語に常に忠実。'
    },

    "Black11": {
      en: '<b>Black11 Frequency</b>, artist from India. Connected to Padang Records through psychedelic frequency. Present on <a href="https://www.instagram.com/black11_frequency/" target="_blank" rel="noopener" style="color:var(--neon-1)">Instagram</a>.',
      es: '<b>Black11 Frequency</b>, artista de la India. Conectado a Padang Records por la frecuencia psicodélica. Presente en <a href="https://www.instagram.com/black11_frequency/" target="_blank" rel="noopener" style="color:var(--neon-1)">Instagram</a>.',
      de: '<b>Black11 Frequency</b>, Künstler aus Indien. Mit Padang Records über die psychedelische Frequenz verbunden. Auf <a href="https://www.instagram.com/black11_frequency/" target="_blank" rel="noopener" style="color:var(--neon-1)">Instagram</a>.',
      fr: '<b>Black11 Frequency</b>, artiste indien. Lié à Padang Records par la fréquence psychédélique. Présent sur <a href="https://www.instagram.com/black11_frequency/" target="_blank" rel="noopener" style="color:var(--neon-1)">Instagram</a>.',
      ja: '<b>Black11 Frequency</b>、インドのアーティスト。サイケデリックな周波数を介して Padang Records と繋がる。<a href="https://www.instagram.com/black11_frequency/" target="_blank" rel="noopener" style="color:var(--neon-1)">Instagram</a> で活動中。'
    },

    "Camps Elisis": {
      en: '<b>Alejandro Camps</b>, born in Mexico City and raised on the southern coast. Started at 12 on guitar and drums; today he crafts immersive soundscapes with deep atmospheric textures. On Padang Records: <b>Quantum Waves</b> (08/2019), <b>The Deserted Forest</b> (08/2025) and <b>Dimension</b>. Delivered <b>Padang Lab Series EP.8</b> as a live set.',
      es: '<b>Alejandro Camps</b>, nacido en Ciudad de México y criado en la costa sur. Empezó a los 12 con guitarra y batería; hoy crea soundscapes inmersivos con texturas atmosféricas profundas. En Padang Records: <b>Quantum Waves</b> (08/2019), <b>The Deserted Forest</b> (08/2025) y <b>Dimension</b>. Presentó <b>Padang Lab Series EP.8</b> en live set.',
      de: '<b>Alejandro Camps</b>, geboren in Mexiko-Stadt, aufgewachsen an der Südküste. Begann mit 12 an Gitarre und Schlagzeug; heute formt er immersive Soundscapes mit tiefen atmosphärischen Texturen. Auf Padang Records: <b>Quantum Waves</b> (08/2019), <b>The Deserted Forest</b> (08/2025) und <b>Dimension</b>. Lieferte <b>Padang Lab Series EP.8</b> als Live-Set.',
      fr: '<b>Alejandro Camps</b>, né à Mexico et élevé sur la côte sud. A commencé à 12 ans à la guitare et à la batterie; aujourd\\\'hui il façonne des soundscapes immersifs aux textures atmosphériques profondes. Sur Padang Records : <b>Quantum Waves</b> (08/2019), <b>The Deserted Forest</b> (08/2025) et <b>Dimension</b>. A livré <b>Padang Lab Series EP.8</b> en live set.',
      ja: '<b>Alejandro Camps</b>、メキシコシティ生まれ、南海岸育ち。12歳でギターとドラムを始め、今では深いアトモスフェリックなテクスチャを持つ没入型サウンドスケープを構築。Padang Records からは <b>Quantum Waves</b>（2019年8月）、<b>The Deserted Forest</b>（2025年8月）、<b>Dimension</b> をリリース。<b>Padang Lab Series EP.8</b> をライブセットで披露。'
    },

    "Champirolls": {
      en: '<b>Julien Poujol</b>, Toulouse, France. Dark Progressive project born in 2015 — "pure, unfiltered energy straight from the underground: rolling basslines, deep grooves, stripped-down hypnotic intensity". Released on Padang Records and headlined <b>Padang Lab Series EP.20</b> (19/12/2025). Recent festivals: Hadra 2025, Boom Festival 2025, Nataraja, Bucht der Träumer 2024. Contact: champirollsmusic@gmail.com.',
      es: '<b>Julien Poujol</b>, Toulouse, Francia. Proyecto Dark Progressive creado en 2015 — "pure, unfiltered energy straight from the underground: rolling basslines, deep grooves, stripped-down hypnotic intensity". Lanzó en Padang Records y protagonizó <b>Padang Lab Series EP.20</b> (19/12/2025). Festivales recientes: Hadra 2025, Boom Festival 2025, Nataraja, Bucht der Träumer 2024. Contacto: champirollsmusic@gmail.com.',
      de: '<b>Julien Poujol</b>, Toulouse, Frankreich. Dark-Progressive-Projekt seit 2015 — "pure, unfiltered energy straight from the underground: rolling basslines, deep grooves, stripped-down hypnotic intensity". Veröffentlicht auf Padang Records und Mittelpunkt der <b>Padang Lab Series EP.20</b> (19.12.2025). Aktuelle Festivals: Hadra 2025, Boom Festival 2025, Nataraja, Bucht der Träumer 2024. Kontakt: champirollsmusic@gmail.com.',
      fr: '<b>Julien Poujol</b>, Toulouse, France. Projet Dark Progressive né en 2015 — « pure, unfiltered energy straight from the underground : rolling basslines, deep grooves, stripped-down hypnotic intensity ». Sorti sur Padang Records et a porté la <b>Padang Lab Series EP.20</b> (19/12/2025). Festivals récents : Hadra 2025, Boom Festival 2025, Nataraja, Bucht der Träumer 2024. Contact : champirollsmusic@gmail.com.',
      ja: '<b>Julien Poujol</b>、フランス・トゥールーズ出身。2015年に始まった Dark Progressive プロジェクト — 「pure, unfiltered energy straight from the underground: rolling basslines, deep grooves, stripped-down hypnotic intensity」。Padang Records からリリースし、<b>Padang Lab Series EP.20</b>（2025年12月19日）を牽引。最近のフェス：Hadra 2025、Boom Festival 2025、Nataraja、Bucht der Träumer 2024。連絡先: champirollsmusic@gmail.com。'
    },

    "Dienstmann": {
      en: '<b>Carlos Dienstmann</b>, Novo Hamburgo (BR). <b>Founder and curator of Padang Records</b> — "two decades shaping underground music, events, and artist curatorship". Style: minimalist psychedelia dominated by strong techno influences. <b>On Padang Records:</b> <b>Circuit Breakdown EP</b> (20/10/2021) — 4 tracks (Data Railway, Circuit Breakdown, No Duality, The Proxy 2 with Vorg); <b>Aka Brujo</b> (03/2022); <b>Offline Providings</b> (03/2022); collaboration <b>Fractal Dimensions</b> (Dienstmann vs Vorg). Delivered <b>Padang Lab Series EP.10</b> as a live set. The vision and artistic direction behind every Padang release.',
      es: '<b>Carlos Dienstmann</b>, Novo Hamburgo (BR). <b>Fundador y curador de Padang Records</b> — "two decades shaping underground music, events, and artist curatorship". Estilo: psicodelia minimalista dominada por fuertes influencias techno. <b>En Padang Records:</b> <b>Circuit Breakdown EP</b> (20/10/2021) — 4 tracks (Data Railway, Circuit Breakdown, No Duality, The Proxy 2 con Vorg); <b>Aka Brujo</b> (03/2022); <b>Offline Providings</b> (03/2022); colaboración <b>Fractal Dimensions</b> (Dienstmann vs Vorg). Presentó <b>Padang Lab Series EP.10</b> en live set. Visión y dirección artística detrás de toda la discografía Padang.',
      de: '<b>Carlos Dienstmann</b>, Novo Hamburgo (BR). <b>Gründer und Kurator von Padang Records</b> — "two decades shaping underground music, events, and artist curatorship". Stil: minimalistische Psychedelia, geprägt von starken Techno-Einflüssen. <b>Auf Padang Records:</b> <b>Circuit Breakdown EP</b> (20.10.2021) — 4 Tracks (Data Railway, Circuit Breakdown, No Duality, The Proxy 2 mit Vorg); <b>Aka Brujo</b> (03/2022); <b>Offline Providings</b> (03/2022); Kollaboration <b>Fractal Dimensions</b> (Dienstmann vs Vorg). Lieferte <b>Padang Lab Series EP.10</b> als Live-Set. Vision und künstlerische Leitung hinter jeder Padang-Veröffentlichung.',
      fr: '<b>Carlos Dienstmann</b>, Novo Hamburgo (BR). <b>Fondateur et curateur de Padang Records</b> — « two decades shaping underground music, events, and artist curatorship ». Style : psychédélie minimaliste dominée par de fortes influences techno. <b>Sur Padang Records :</b> <b>Circuit Breakdown EP</b> (20/10/2021) — 4 morceaux (Data Railway, Circuit Breakdown, No Duality, The Proxy 2 avec Vorg); <b>Aka Brujo</b> (03/2022); <b>Offline Providings</b> (03/2022); collaboration <b>Fractal Dimensions</b> (Dienstmann vs Vorg). A livré <b>Padang Lab Series EP.10</b> en live set. Vision et direction artistique derrière chaque sortie Padang.',
      ja: '<b>Carlos Dienstmann</b>、ブラジル・ノヴォ・アンブルゴ出身。<b>Padang Records の創設者兼キュレーター</b> — 「two decades shaping underground music, events, and artist curatorship」（アンダーグラウンド音楽・イベント・アーティスト・キュレーションを 20 年にわたって形作る）。スタイル：強いテクノの影響に支配された、ミニマリスティックなサイケデリア。<b>Padang Records から：</b><b>Circuit Breakdown EP</b>（2021年10月20日） — 4トラック（Data Railway、Circuit Breakdown、No Duality、Vorg との The Proxy 2）；<b>Aka Brujo</b>（2022年3月）；<b>Offline Providings</b>（2022年3月）；コラボ <b>Fractal Dimensions</b>（Dienstmann vs Vorg）。<b>Padang Lab Series EP.10</b> をライブセットで披露。Padang のすべてのリリースを貫くビジョンとアーティスティック・ディレクション。'
    },

    "Diorama": {
      en: '<b>Nikhil Harpalani</b>, Dubai/India. Known for his signature blend of <b>bouncy dark progressive</b> on Padang Records. DJ since 2015, performing across the Middle East and various regions of India, steadily building a reputation for immersive and energetic sets. A devoted psychedelic music enthusiast since the late 1990s — two decades curating and collecting intelligent, forward-thinking sounds. Contributed several compilations to the label. Contact: nikhil_harpalani@hotmail.com.',
      es: '<b>Nikhil Harpalani</b>, Dubái/India. Conocido por su signature blend de <b>bouncy dark progressive</b> en Padang Records. DJ desde 2015, performando por el Medio Oriente y varias regiones de la India, construyendo reputación por sets inmersivos y enérgicos. Entusiasta de la música psicodélica desde finales de los años 1990 — dos décadas curando y coleccionando sonidos inteligentes y forward-thinking. Contribuyó varias compilaciones al sello. Contacto: nikhil_harpalani@hotmail.com.',
      de: '<b>Nikhil Harpalani</b>, Dubai/Indien. Bekannt für seinen unverwechselbaren Blend aus <b>bouncy Dark Progressive</b> auf Padang Records. DJ seit 2015 mit Auftritten im Nahen Osten und verschiedenen Regionen Indiens, baut stetig einen Ruf für immersive und energetische Sets auf. Hingebungsvoller Liebhaber psychedelischer Musik seit Ende der 1990er — zwei Jahrzehnte des Kuratierens und Sammelns intelligenter, vorwärtsdenkender Sounds. Hat mehrere Compilations zum Label beigetragen. Kontakt: nikhil_harpalani@hotmail.com.',
      fr: '<b>Nikhil Harpalani</b>, Dubaï/Inde. Connu pour son blend signature de <b>bouncy dark progressive</b> sur Padang Records. DJ depuis 2015, performant à travers le Moyen-Orient et différentes régions d\'Inde, construisant régulièrement une réputation pour des sets immersifs et énergiques. Passionné de musique psychédélique depuis la fin des années 1990 — deux décennies à curater et collectionner des sons intelligents et forward-thinking. A contribué à plusieurs compilations du label. Contact : nikhil_harpalani@hotmail.com.',
      ja: '<b>Nikhil Harpalani</b>、ドバイ／インド出身。Padang Records における <b>bouncy dark progressive</b> のシグネチャー・ブレンドで知られる。2015年から DJ として活動、中東とインド各地でパフォーマンスを行い、没入的でエネルギッシュなセットで評価を築いてきた。1990年代後半からの熱心なサイケデリック・ミュージック愛好家 — 知的で先見性のあるサウンドを20年にわたってキュレーション＆コレクション。レーベルに複数のコンピレーションを寄稿。連絡先: nikhil_harpalani@hotmail.com。'
    },

    "Fevered Shiva": {
      en: 'Berlin-based, originally from Australia. "Described by his neighbours as definitely not a musician" — his music is full of creak, growl and rumble that summon curious bunyips to the dancefloor. Releases on Padang Records: <b>Inside Out</b>, <b>Klaranoia</b>, <b>Scattered Pattern</b>, <b>Bug\\\'s Life</b> and <b>Sanskritzophrenia</b>. Released an album with Version Bizar in 08/2018.',
      es: 'Radicado en Berlín, originalmente de Australia. "Described by his neighbours as definitely not a musician" — su música está llena de creak, growl y rumble que invocan bunyips curiosos al dancefloor. Releases en Padang Records: <b>Inside Out</b>, <b>Klaranoia</b>, <b>Scattered Pattern</b>, <b>Bug\\\'s Life</b> y <b>Sanskritzophrenia</b>. Lanzó un álbum con Version Bizar en 08/2018.',
      de: 'In Berlin ansässig, ursprünglich aus Australien. "Described by his neighbours as definitely not a musician" — seine Musik ist voll von Knarren, Knurren und Rumpeln, die neugierige Bunyips auf die Tanzfläche locken. Releases auf Padang Records: <b>Inside Out</b>, <b>Klaranoia</b>, <b>Scattered Pattern</b>, <b>Bug\\\'s Life</b> und <b>Sanskritzophrenia</b>. Album mit Version Bizar im 08/2018.',
      fr: 'Basé à Berlin, originaire d\\\'Australie. « Described by his neighbours as definitely not a musician » — sa musique est pleine de craquements, de grognements et de grondements qui attirent les bunyips curieux sur la piste. Sorties chez Padang Records : <b>Inside Out</b>, <b>Klaranoia</b>, <b>Scattered Pattern</b>, <b>Bug\\\'s Life</b> et <b>Sanskritzophrenia</b>. Album avec Version Bizar en 08/2018.',
      ja: 'ベルリン拠点、オーストラリア出身。「Described by his neighbours as definitely not a musician」 — 軋み、唸り、轟きに満ちた彼の音楽は、好奇心旺盛な bunyips をダンスフロアへ呼び寄せる。Padang Records からのリリース：<b>Inside Out</b>、<b>Klaranoia</b>、<b>Scattered Pattern</b>、<b>Bug\\\'s Life</b>、<b>Sanskritzophrenia</b>。2018年8月に Version Bizar とアルバムをリリース。'
    },

    "Fughetta & Fugato": {
      en: '<b>Huiya Fughetta</b> (southern China) and <b>Ricardo Fugato</b> (Ecuadorian Andes), based in Zürich, Switzerland. Psychedelic live act — deep groovy basses with classical elements, experimental ambient textures and crispy FM leads. Inspired by human languages, nature and indigenous sounds. On Padang Records: <b>Ubuntu</b> with Epistemikk (07/2024). Contact: fughetta.fugato@gmail.com.',
      es: '<b>Huiya Fughetta</b> (sur de China) y <b>Ricardo Fugato</b> (Andes ecuatorianos), basados en Zúrich, Suiza. Live act psicodélico — graves groovy profundos con elementos clásicos, texturas experimentales ambient y leads FM crispy. Inspirados en lenguas humanas, naturaleza y sonidos indígenas. En Padang Records: <b>Ubuntu</b> con Epistemikk (07/2024). Contacto: fughetta.fugato@gmail.com.',
      de: '<b>Huiya Fughetta</b> (Südchina) und <b>Ricardo Fugato</b> (ecuadorianische Anden), ansässig in Zürich, Schweiz. Psychedelischer Live-Act — tiefe groovige Bässe mit klassischen Elementen, experimentellen Ambient-Texturen und knackigen FM-Leads. Inspiriert von menschlichen Sprachen, Natur und indigenen Klängen. Auf Padang Records: <b>Ubuntu</b> mit Epistemikk (07/2024). Kontakt: fughetta.fugato@gmail.com.',
      fr: '<b>Huiya Fughetta</b> (sud de la Chine) et <b>Ricardo Fugato</b> (Andes équatoriennes), basés à Zurich, Suisse. Live act psychédélique — basses groovy profondes avec éléments classiques, textures ambient expérimentales et leads FM crispy. Inspirés par les langues humaines, la nature et les sons autochtones. Sur Padang Records : <b>Ubuntu</b> avec Epistemikk (07/2024). Contact : fughetta.fugato@gmail.com.',
      ja: '<b>Huiya Fughetta</b>（中国南部）と <b>Ricardo Fugato</b>（エクアドル・アンデス）、スイス・チューリッヒ拠点。サイケデリックなライブアクト — クラシックの要素を持つグルーヴィーで深いベース、実験的なアンビエント・テクスチャ、クリスピーな FM リード。人間の言語、自然、先住民の音にインスパイアされる。Padang Records から <b>Ubuntu</b>（Epistemikk と共演、2024年7月）。連絡先: fughetta.fugato@gmail.com。'
    },

    "Green Waves": {
      en: '<b>Artur</b>, Belo Horizonte / Ouro Branco-MG. Started on drums at 12, influenced by his father (a rock DJ in the 80s-90s); at 14 he moved into electronic music and production. On Padang Records: <b>Chronicles</b> (10/2025, 10 tracks) and <b>Surfing in Oscillations</b> (05/2023). Collaboration <b>Bon Voyage</b> with Slip Hypnotic.',
      es: '<b>Artur</b>, Belo Horizonte / Ouro Branco-MG. Empezó tocando batería a los 12, influenciado por su padre (DJ de rock en los 80-90); a los 14 migró a la electrónica y la producción. En Padang Records: <b>Chronicles</b> (10/2025, 10 tracks) y <b>Surfing in Oscillations</b> (05/2023). Colaboración <b>Bon Voyage</b> con Slip Hypnotic.',
      de: '<b>Artur</b>, Belo Horizonte / Ouro Branco-MG. Begann mit 12 am Schlagzeug, beeinflusst von seinem Vater (Rock-DJ in den 80er-90er Jahren); mit 14 wechselte er zur elektronischen Musik und Produktion. Auf Padang Records: <b>Chronicles</b> (10/2025, 10 Tracks) und <b>Surfing in Oscillations</b> (05/2023). Kollaboration <b>Bon Voyage</b> mit Slip Hypnotic.',
      fr: '<b>Artur</b>, Belo Horizonte / Ouro Branco-MG. A commencé à la batterie à 12 ans, influencé par son père (DJ rock des années 80-90); à 14 ans, il bascule vers la musique électronique et la production. Sur Padang Records : <b>Chronicles</b> (10/2025, 10 morceaux) et <b>Surfing in Oscillations</b> (05/2023). Collaboration <b>Bon Voyage</b> avec Slip Hypnotic.',
      ja: '<b>Artur</b>、ブラジル・ベロオリゾンテ／オウロ・ブランコ-MG。12歳でドラムを始め（父親が80-90年代のロック DJ だった影響）、14歳でエレクトロニック音楽と制作へ移行。Padang Records から：<b>Chronicles</b>（2025年10月、10トラック）、<b>Surfing in Oscillations</b>（2023年5月）。Slip Hypnotic とのコラボ <b>Bon Voyage</b>。'
    },

    "Groovy Smoothy": {
      en: 'DJ and producer from Darmstadt, Germany — building a groovy psychedelia with agile pulse, slippery basslines and precise dynamics. Released <b>Advent of the Submerged</b> on Padang Records (01/2026).',
      es: 'DJ y productor de Darmstadt, Alemania — construyendo una psicodelia groovy de pulso ágil, basslines escurridizos y dinámica precisa. Lanzó <b>Advent of the Submerged</b> en Padang Records (01/2026).',
      de: 'DJ und Produzent aus Darmstadt, Deutschland — baut eine groovige Psychedelia mit agilem Puls, schlüpfrigen Basslines und präziser Dynamik. Veröffentlichte <b>Advent of the Submerged</b> auf Padang Records (01/2026).',
      fr: 'DJ et producteur de Darmstadt, Allemagne — construit une psychédélie groovy au pouls agile, aux basslines glissantes et à la dynamique précise. A sorti <b>Advent of the Submerged</b> sur Padang Records (01/2026).',
      ja: 'ドイツ・ダルムシュタット出身の DJ ／プロデューサー — 機敏なパルス、すべるベースライン、緻密なダイナミクスを持つグルーヴィーなサイケデリアを構築。Padang Records から <b>Advent of the Submerged</b>（2026年1月）をリリース。'
    },

    "Headweller": {
      en: '<b>Christos Chouvardas</b>, Thessaloniki, Greece. Unique in fusing spiritual evolution with rhythm and movement. Delivered <b>Padang Lab Series EP.1</b>. On Padang Records: <b>The Weight of Thought</b> (07/2025) and <b>The Cruellest Master</b> (VA Reborn). In 2022 he began composing ambient music for dance-theatre and short films. Festivals: Shankra (CH), Tree Of Life (TR), Solstice (NL), Revision (GR).',
      es: '<b>Christos Chouvardas</b>, Tesalónica, Grecia. Único en fusionar evolución espiritual con ritmo y movimiento. Presentó <b>Padang Lab Series EP.1</b>. En Padang Records: <b>The Weight of Thought</b> (07/2025) y <b>The Cruellest Master</b> (VA Reborn). En 2022 empezó a componer música ambient para dance-theatre y cortos. Festivales: Shankra (CH), Tree Of Life (TR), Solstice (NL), Revision (GR).',
      de: '<b>Christos Chouvardas</b>, Thessaloniki, Griechenland. Einzigartig in der Verschmelzung spiritueller Evolution mit Rhythmus und Bewegung. Lieferte <b>Padang Lab Series EP.1</b>. Auf Padang Records: <b>The Weight of Thought</b> (07/2025) und <b>The Cruellest Master</b> (VA Reborn). 2022 begann er, Ambient-Musik für Tanztheater und Kurzfilme zu komponieren. Festivals: Shankra (CH), Tree Of Life (TR), Solstice (NL), Revision (GR).',
      fr: '<b>Christos Chouvardas</b>, Thessalonique, Grèce. Unique dans sa fusion entre évolution spirituelle, rythme et mouvement. A livré <b>Padang Lab Series EP.1</b>. Sur Padang Records : <b>The Weight of Thought</b> (07/2025) et <b>The Cruellest Master</b> (VA Reborn). En 2022 il commence à composer de la musique ambient pour le dance-theatre et le court-métrage. Festivals : Shankra (CH), Tree Of Life (TR), Solstice (NL), Revision (GR).',
      ja: '<b>Christos Chouvardas</b>、ギリシャ・テッサロニキ出身。スピリチュアルな進化とリズム・動きの融合において独自の存在。<b>Padang Lab Series EP.1</b> を披露。Padang Records から：<b>The Weight of Thought</b>（2025年7月）、<b>The Cruellest Master</b>（VA Reborn）。2022年からダンス・シアターと短編映画のためのアンビエント音楽の制作を開始。フェス：Shankra（CH）、Tree Of Life（TR）、Solstice（NL）、Revision（GR）。'
    },

    "Jandri": {
      en: '<b>Jandri</b>, Spain (Torrijos/Barcelona). Musical journey began in 2008 as <b>Guther</b> on the Drum and Bass scene with classic vinyl. The Jandri project was born in 2023 — fusing subgenres of <b>minimal techno (com pitada de psy)</b>. <b>Venues:</b> Club Zoreks (Lleida), Sala Golfus (Tarragona), Mama Mandawa (Barcelona), Florida 135 (Huesca), Sala Tren (Granada), Sala On (Madrid). <b>Festivals:</b> Moontagood Festival, Misa Psycodélika (Barcelona), The End of the World (Tarragona), Own Spirit Festival (Aragón), Arkana (Barcelona), Transition Fest. (Andalusia), La Casba Fest. (France), Visionart Fest. (Barcelona), Bass in the Park (Barcelona). Contact: jandri.minimal techno com pitada de psy@gmail.com.',
      es: '<b>Jandri</b>, España (Torrijos/Barcelona). El viaje musical comenzó en 2008 como <b>Guther</b> en la escena del Drum and Bass con vinilos clásicos. En 2023 nace el proyecto Jandri — fusión de subgéneros del <b>minimal techno (com pitada de psy)</b>. <b>Venues:</b> Club Zoreks (Lleida), Sala Golfus (Tarragona), Mama Mandawa (Barcelona), Florida 135 (Huesca), Sala Tren (Granada), Sala On (Madrid). <b>Festivales:</b> Moontagood Festival, Misa Psycodélika (Barcelona), The End of the World (Tarragona), Own Spirit Festival (Aragón), Arkana (Barcelona), Transition Fest. (Andalucía), La Casba Fest. (Francia), Visionart Fest. (Barcelona), Bass in the Park (Barcelona). Contacto: jandri.minimal techno com pitada de psy@gmail.com.',
      de: '<b>Jandri</b>, Spanien (Torrijos/Barcelona). Die musikalische Reise begann 2008 als <b>Guther</b> in der Drum-and-Bass-Szene mit klassischem Vinyl. 2023 entstand das Projekt Jandri — Fusion von Subgenres des <b>minimal techno (com pitada de psy)</b>. <b>Venues:</b> Club Zoreks (Lleida), Sala Golfus (Tarragona), Mama Mandawa (Barcelona), Florida 135 (Huesca), Sala Tren (Granada), Sala On (Madrid). <b>Festivals:</b> Moontagood Festival, Misa Psycodélika (Barcelona), The End of the World (Tarragona), Own Spirit Festival (Aragón), Arkana (Barcelona), Transition Fest. (Andalusien), La Casba Fest. (Frankreich), Visionart Fest. (Barcelona), Bass in the Park (Barcelona). Kontakt: jandri.minimal techno com pitada de psy@gmail.com.',
      fr: '<b>Jandri</b>, Espagne (Torrijos/Barcelone). Le parcours musical a débuté en 2008 sous le nom de <b>Guther</b> dans la scène Drum and Bass avec du vinyle classique. Le projet Jandri est né en 2023 — fusion de sous-genres du <b>minimal techno (com pitada de psy)</b>. <b>Salles :</b> Club Zoreks (Lleida), Sala Golfus (Tarragone), Mama Mandawa (Barcelone), Florida 135 (Huesca), Sala Tren (Grenade), Sala On (Madrid). <b>Festivals :</b> Moontagood Festival, Misa Psycodélika (Barcelone), The End of the World (Tarragone), Own Spirit Festival (Aragon), Arkana (Barcelone), Transition Fest. (Andalousie), La Casba Fest. (France), Visionart Fest. (Barcelone), Bass in the Park (Barcelone). Contact : jandri.minimal techno com pitada de psy@gmail.com.',
      ja: '<b>Jandri</b>、スペイン（トリホス／バルセロナ）出身。2008年に <b>Guther</b> 名義で Drum and Bass シーンに入り、クラシックなヴァイナルでキャリアを始める。2023年に Jandri プロジェクトを開始 — <b>minimal techno (com pitada de psy)</b> のサブジャンルを融合。<b>会場:</b> Club Zoreks（リェイダ）、Sala Golfus（タラゴナ）、Mama Mandawa（バルセロナ）、Florida 135（ウエスカ）、Sala Tren（グラナダ）、Sala On（マドリード）。<b>フェスティバル:</b> Moontagood Festival、Misa Psycodélika（バルセロナ）、The End of the World（タラゴナ）、Own Spirit Festival（アラゴン）、Arkana（バルセロナ）、Transition Fest.（アンダルシア）、La Casba Fest.（フランス）、Visionart Fest.（バルセロナ）、Bass in the Park（バルセロナ）。連絡先: jandri.minimal techno com pitada de psy@gmail.com。'
    },

    "Jungle Haze": {
      en: 'Mexican dark progressive producer. On Padang Records: <b>Xaman</b> (10/2018), <b>Species</b> and <b>Sacred Ritual EP</b>. Collaborated with Stopless on the <b>Technochtitlan EP</b> in 2018.',
      es: 'Productor mexicano de dark progressive. En Padang Records: <b>Xaman</b> (10/2018), <b>Species</b> y <b>Sacred Ritual EP</b>. Colaboró con Stopless en el <b>Technochtitlan EP</b> en 2018.',
      de: 'Mexikanischer Dark-Progressive-Produzent. Auf Padang Records: <b>Xaman</b> (10/2018), <b>Species</b> und <b>Sacred Ritual EP</b>. Kollaboration mit Stopless auf der <b>Technochtitlan EP</b> 2018.',
      fr: 'Producteur mexicain de dark progressive. Sur Padang Records : <b>Xaman</b> (10/2018), <b>Species</b> et <b>Sacred Ritual EP</b>. A collaboré avec Stopless sur le <b>Technochtitlan EP</b> en 2018.',
      ja: 'メキシコの dark progressive プロデューサー。Padang Records から：<b>Xaman</b>（2018年10月）、<b>Species</b>、<b>Sacred Ritual EP</b>。2018年に Stopless と <b>Technochtitlan EP</b> でコラボ。'
    },

    "Kaylee": {
      en: '<b>Michelle Kelly Leemann</b>, Zürich / NYC. DJ and producer — Techno and Night-Psychedelic Trance. Also performs as <b>KAYLEE!</b>. Wife of Suspect One (Robert Reuss); their joint project <b>Art Materials</b> bridges Techno and Psy. Creator of <b>MODULAR FESTIVAL</b>. Part of the Padang Records crew.',
      es: '<b>Michelle Kelly Leemann</b>, Zúrich / NYC. DJ y productora — Techno y Night-Psychedelic Trance. También se presenta como <b>KAYLEE!</b>. Esposa de Suspect One (Robert Reuss); el proyecto conjunto <b>Art Materials</b> tiende un puente creativo entre Techno y Psy. Creadora del <b>MODULAR FESTIVAL</b>. Integra el equipo de Padang Records.',
      de: '<b>Michelle Kelly Leemann</b>, Zürich / NYC. DJ und Produzentin — Techno und Night-Psychedelic Trance. Tritt auch als <b>KAYLEE!</b> auf. Verheiratet mit Suspect One (Robert Reuss); das gemeinsame Projekt <b>Art Materials</b> schlägt eine kreative Brücke zwischen Techno und Psy. Schöpferin des <b>MODULAR FESTIVAL</b>. Teil des Padang-Records-Teams.',
      fr: '<b>Michelle Kelly Leemann</b>, Zurich / NYC. DJ et productrice — Techno et Night-Psychedelic Trance. Se produit également sous <b>KAYLEE!</b>. Épouse de Suspect One (Robert Reuss); leur projet commun <b>Art Materials</b> fait le pont créatif entre Techno et Psy. Créatrice du <b>MODULAR FESTIVAL</b>. Membre de l\\\'équipe Padang Records.',
      ja: '<b>Michelle Kelly Leemann</b>、チューリッヒ／NYC 拠点。DJ ／プロデューサー — Techno と Night-Psychedelic Trance。<b>KAYLEE!</b> としても活動。Suspect One（Robert Reuss）の配偶者。共同プロジェクト <b>Art Materials</b> は Techno と Psy をつなぐ創造的な橋。<b>MODULAR FESTIVAL</b> の創設者。Padang Records チームの一員。'
    },

    "Kilbee": {
      en: '<b>Gabriel Gómez</b> — Chile (Concepción / Santiago). Kilbee is one of the aliases of Rollercoaster / Paracoaster / Arcturians / Gao. As Kilbee he explores the most hypnotic side of psytrance, with minimalist constructions and a focus on detail.',
      es: '<b>Gabriel Gómez</b> — Chile (Concepción / Santiago). Kilbee es uno de los alias de Rollercoaster / Paracoaster / Arcturians / Gao. Como Kilbee explora la vertiente más hipnótica del psytrance, con construcciones minimalistas y foco en el detalle.',
      de: '<b>Gabriel Gómez</b> — Chile (Concepción / Santiago). Kilbee ist eines der Aliase von Rollercoaster / Paracoaster / Arcturians / Gao. Als Kilbee erforscht er die hypnotischste Seite des Psytrance — minimalistische Konstruktionen mit Detailfokus.',
      fr: '<b>Gabriel Gómez</b> — Chili (Concepción / Santiago). Kilbee est l\\\'un des alias de Rollercoaster / Paracoaster / Arcturians / Gao. Sous Kilbee, il explore le versant le plus hypnotique du psytrance — constructions minimalistes et précision du détail.',
      ja: '<b>Gabriel Gómez</b> — チリ（コンセプシオン／サンティアゴ）。Kilbee は Rollercoaster／Paracoaster／Arcturians／Gao のエイリアスの一つ。Kilbee 名義では、ミニマリスティックな構築と細部への集中で psytrance のもっとも催眠的な側面を探求。'
    },

    "Mallki": {
      en: '"Domestic Pirates". Peruvian based in Barcelona, <b>official Padang Records DJ</b>. Creator of <b>Arkana Festival</b> — 13+ years in the Sacred Valley of the Incas, Peru. Versatile DJ moving between downtempo, progressive house, deep house, techno, minimal techno and psytrance. <br><br><b>South America:</b> Universo Paralello (UP Club · BR), Pulsar Festival, Zubuya, Terra em Transe, Resonar, Aho Festival (BR), Earthdance Argentina, Inchala (Uruguay), Amazonas Andes (Bolivia), Arkana Festival (Peru). <b>Mexico:</b> Ometeotl, Psycristrance, Ocelot, Space Odissey 3, Promise Land, Poison Festival, MoDem teaser MX. <b>Europe:</b> Bermuda Gathering (Finland), Own Spirit Festival (Spain), Atman Festival (Portugal), Eudaimonia Gathering (Greece), MO:DEM (Croatia), Suti Festival (Portugal). Curated <b>VA Nukaya</b> (Padang Records, 05/2024) — 19 global producers with reborn Inca rhythms.',
      es: '"Domestic Pirates". Peruano radicado en Barcelona, <b>DJ oficial de Padang Records</b>. Creador del <b>Arkana Festival</b> — 13+ años en el Valle Sagrado de los Incas, Perú. DJ versátil que transita por downtempo, progressive house, deep house, techno, minimal techno y psytrance. <br><br><b>Sudamérica:</b> Universo Paralello (UP Club · BR), Pulsar Festival, Zubuya, Terra em Transe, Resonar, Aho Festival (BR), Earthdance Argentina, Inchala (Uruguay), Amazonas Andes (Bolivia), Arkana Festival (Perú). <b>México:</b> Ometeotl, Psycristrance, Ocelot, Space Odissey 3, Promise Land, Poison Festival, MoDem teaser MX. <b>Europa:</b> Bermuda Gathering (Finlandia), Own Spirit Festival (España), Atman Festival (Portugal), Eudaimonia Gathering (Grecia), MO:DEM (Croacia), Suti Festival (Portugal). Curó <b>VA Nukaya</b> (Padang Records, 05/2024) — 19 productores globales con ritmos Inca renacidos.',
      de: '"Domestic Pirates". Peruaner mit Sitz in Barcelona, <b>offizieller Padang-Records-DJ</b>. Schöpfer des <b>Arkana Festival</b> — 13+ Jahre im Heiligen Tal der Inka, Peru. Vielseitiger DJ zwischen Downtempo, Progressive House, Deep House, Techno, Minimal Techno und Psytrance. <br><br><b>Südamerika:</b> Universo Paralello (UP Club · BR), Pulsar Festival, Zubuya, Terra em Transe, Resonar, Aho Festival (BR), Earthdance Argentinien, Inchala (Uruguay), Amazonas Andes (Bolivien), Arkana Festival (Peru). <b>Mexiko:</b> Ometeotl, Psycristrance, Ocelot, Space Odissey 3, Promise Land, Poison Festival, MoDem-Teaser MX. <b>Europa:</b> Bermuda Gathering (Finnland), Own Spirit Festival (Spanien), Atman Festival (Portugal), Eudaimonia Gathering (Griechenland), MO:DEM (Kroatien), Suti Festival (Portugal). Kuratierte <b>VA Nukaya</b> (Padang Records, 05/2024) — 19 globale Produzenten mit wiedergeborenen Inka-Rhythmen.',
      fr: '« Domestic Pirates ». Péruvien basé à Barcelone, <b>DJ officiel de Padang Records</b>. Créateur de l\'<b>Arkana Festival</b> — 13+ ans dans la Vallée Sacrée des Incas, Pérou. DJ polyvalent naviguant entre downtempo, progressive house, deep house, techno, minimal techno et psytrance. <br><br><b>Amérique du Sud :</b> Universo Paralello (UP Club · BR), Pulsar Festival, Zubuya, Terra em Transe, Resonar, Aho Festival (BR), Earthdance Argentine, Inchala (Uruguay), Amazonas Andes (Bolivie), Arkana Festival (Pérou). <b>Mexique :</b> Ometeotl, Psycristrance, Ocelot, Space Odissey 3, Promise Land, Poison Festival, MoDem teaser MX. <b>Europe :</b> Bermuda Gathering (Finlande), Own Spirit Festival (Espagne), Atman Festival (Portugal), Eudaimonia Gathering (Grèce), MO:DEM (Croatie), Suti Festival (Portugal). A curaté <b>VA Nukaya</b> (Padang Records, 05/2024) — 19 producteurs internationaux et rythmes incas renaissants.',
      ja: '「Domestic Pirates」。バルセロナ拠点のペルー人、<b>Padang Records 公式 DJ</b>。<b>Arkana Festival</b> の創設者 — ペルー・インカ聖なる谷で13年以上。ダウンテンポ、プログレッシブ・ハウス、ディープ・ハウス、テクノ、ミニマル・テクノ、psytrance を行き来する多才な DJ。<br><br><b>南米：</b>Universo Paralello（UP Club · BR）、Pulsar Festival、Zubuya、Terra em Transe、Resonar、Aho Festival（BR）、Earthdance アルゼンチン、Inchala（ウルグアイ）、Amazonas Andes（ボリビア）、Arkana Festival（ペルー）。<b>メキシコ：</b>Ometeotl、Psycristrance、Ocelot、Space Odissey 3、Promise Land、Poison Festival、MoDem teaser MX。<b>ヨーロッパ：</b>Bermuda Gathering（フィンランド）、Own Spirit Festival（スペイン）、Atman Festival（ポルトガル）、Eudaimonia Gathering（ギリシャ）、MO:DEM（クロアチア）、Suti Festival（ポルトガル）。Padang Records で <b>VA Nukaya</b>（2024年5月）をキュレーション — 世界19組のプロデューサーと甦るインカのリズム。'
    },

    "Massive Psy": {
      en: '<b>Shahabeddin</b>, born in Tehran, Iran. Moved to Armenia in 2007 and was one of the first DJs to introduce psytrance into Armenian nightlife. Dove into Dark Progressive Psytrance and Dark Progressive Techno (Zenonesque). Founder of <b>QUANTUM LAB</b> and <b>NAYAMA FESTIVAL</b>; member of AHOORA FESTIVAL. Part of Padang Records — exclusive set "MASSIVE PSY for PADANG RECORDS" (06/2024). DJ since 2005.',
      es: '<b>Shahabeddin</b>, nacido en Teherán, Irán. Se mudó a Armenia en 2007 y fue uno de los primeros DJs en introducir el psytrance en la vida nocturna armenia. Se sumergió en el Dark Progressive Psytrance y el Dark Progressive Techno (Zenonesque). Fundador de <b>QUANTUM LAB</b> y <b>NAYAMA FESTIVAL</b>; miembro del AHOORA FESTIVAL. Integra Padang Records — set exclusivo "MASSIVE PSY for PADANG RECORDS" (06/2024). DJ desde 2005.',
      de: '<b>Shahabeddin</b>, geboren in Teheran, Iran. 2007 nach Armenien gezogen und einer der ersten DJs, die Psytrance ins armenische Nachtleben brachten. Tauchte in Dark Progressive Psytrance und Dark Progressive Techno (Zenonesque) ein. Gründer von <b>QUANTUM LAB</b> und <b>NAYAMA FESTIVAL</b>; Mitglied des AHOORA FESTIVAL. Teil von Padang Records — exklusives Set "MASSIVE PSY for PADANG RECORDS" (06/2024). DJ seit 2005.',
      fr: '<b>Shahabeddin</b>, né à Téhéran, Iran. A déménagé en Arménie en 2007 et fut l\'un des premiers DJs à introduire le psytrance dans la vie nocturne arménienne. Plongé dans le Dark Progressive Psytrance et le Dark Progressive Techno (Zenonesque). Fondateur de <b>QUANTUM LAB</b> et <b>NAYAMA FESTIVAL</b>; membre de AHOORA FESTIVAL. Intègre Padang Records — set exclusif « MASSIVE PSY for PADANG RECORDS » (06/2024). DJ depuis 2005.',
      ja: '<b>Shahabeddin</b>、イラン・テヘラン生まれ。2007年にアルメニアへ移り、アルメニアのナイトライフに psytrance を持ち込んだ最初の DJ の一人。Dark Progressive Psytrance と Dark Progressive Techno（Zenonesque）に深く没入。<b>QUANTUM LAB</b> と <b>NAYAMA FESTIVAL</b> の創設者、AHOORA FESTIVAL のメンバー。Padang Records の一員 — エクスクルーシブ・セット「MASSIVE PSY for PADANG RECORDS」（2024年6月）。2005年から DJ 活動。'
    },

    "Meerkat": {
      en: '<b>Mark Ahessy</b>, Dublin / southern Ireland. Solo project that started as DJ and moved into production — blend of <b>psy-tech, psygressive and dark progressive</b>. Founder of <b>Enter Mushroom Festival</b> (Ireland). On Padang Records: <b>2 Minutes to Midnight</b> (02/2020), <b>Sodium Pentathol</b> with Zentrix and <b>Project Brue Beam</b> (VA Nukaya). Festivals: Lost Theory, Sunshine, Arkana, Solstice, Ometeotl.',
      es: '<b>Mark Ahessy</b>, Dublín / sur de Irlanda. Proyecto solo que empezó como DJ y migró a la producción — blend de <b>psy-tech, psygressive y dark progressive</b>. Fundador del <b>Enter Mushroom Festival</b> (Irlanda). En Padang Records: <b>2 Minutes to Midnight</b> (02/2020), <b>Sodium Pentathol</b> con Zentrix y <b>Project Brue Beam</b> (VA Nukaya). Festivales: Lost Theory, Sunshine, Arkana, Solstice, Ometeotl.',
      de: '<b>Mark Ahessy</b>, Dublin / Süd-Irland. Solo-Projekt, das als DJ begann und in die Produktion wechselte — Mischung aus <b>Psy-Tech, Psygressive und Dark Progressive</b>. Gründer des <b>Enter Mushroom Festival</b> (Irland). Auf Padang Records: <b>2 Minutes to Midnight</b> (02/2020), <b>Sodium Pentathol</b> mit Zentrix und <b>Project Brue Beam</b> (VA Nukaya). Festivals: Lost Theory, Sunshine, Arkana, Solstice, Ometeotl.',
      fr: '<b>Mark Ahessy</b>, Dublin / sud de l\\\'Irlande. Projet solo né dans le DJing puis tourné vers la production — mélange de <b>psy-tech, psygressive et dark progressive</b>. Fondateur de <b>Enter Mushroom Festival</b> (Irlande). Sur Padang Records : <b>2 Minutes to Midnight</b> (02/2020), <b>Sodium Pentathol</b> avec Zentrix et <b>Project Brue Beam</b> (VA Nukaya). Festivals : Lost Theory, Sunshine, Arkana, Solstice, Ometeotl.',
      ja: '<b>Mark Ahessy</b>、ダブリン／アイルランド南部。DJ から始まり制作へと移行したソロ・プロジェクト — <b>psy-tech、psygressive、dark progressive</b> のブレンド。<b>Enter Mushroom Festival</b>（アイルランド）の創設者。Padang Records から：<b>2 Minutes to Midnight</b>（2020年2月）、Zentrix と <b>Sodium Pentathol</b>、<b>Project Brue Beam</b>（VA Nukaya）。フェス：Lost Theory、Sunshine、Arkana、Solstice、Ometeotl。'
    },

    "Musgolino": {
      en: '<b>Pablo Larrán</b>, Madrid, Spain. Creative mind crafting musical fantasies through dark landscapes, organic textures and cinematic atmospheres. Hypnotic pulse of techno meets immersive depth of progressive. Since 2018 consolidated with releases on Padang Records. <b>Festivals:</b> Own Spirit, Living Village, We Dark One. Active in Spain\'s psychedelic scene as artist and event organizer for 10+ years. On Padang Records: <b>What?</b> (Technomad II, 05/2025), <b>Reminiscencias</b> (VA Nukaya, 05/2024) and <b>Orgelon</b>. Live with Monkey Mind at Own Spirit 2023. Contact: musgolino.music@gmail.com.',
      es: '<b>Pablo Larrán</b>, Madrid, España. Mente creativa que desarrolla fantasías musicales mediante paisajes oscuros, texturas orgánicas y atmósferas cinematográficas. Pulso hipnótico del techno y profundidad inmersiva del progressive. Desde 2018 consolidado con releases en Padang Records. <b>Festivales:</b> Own Spirit, Living Village, We Dark One. Activo en la escena psicodélica española como artista y organizador hace 10+ años. En Padang Records: <b>What?</b> (Technomad II, 05/2025), <b>Reminiscencias</b> (VA Nukaya, 05/2024) y <b>Orgelon</b>. Live con Monkey Mind en Own Spirit 2023. Contacto: musgolino.music@gmail.com.',
      de: '<b>Pablo Larrán</b>, Madrid, Spanien. Kreativer Kopf, der musikalische Fantasien durch dunkle Landschaften, organische Texturen und filmische Atmosphären entwickelt. Hypnotischer Techno-Puls trifft auf immersive Progressive-Tiefe. Seit 2018 mit Veröffentlichungen auf Padang Records konsolidiert. <b>Festivals:</b> Own Spirit, Living Village, We Dark One. Aktiv in Spaniens psychedelischer Szene als Künstler und Eventorganisator seit 10+ Jahren. Auf Padang Records: <b>What?</b> (Technomad II, 05/2025), <b>Reminiscencias</b> (VA Nukaya, 05/2024) und <b>Orgelon</b>. Live mit Monkey Mind beim Own Spirit 2023. Kontakt: musgolino.music@gmail.com.',
      fr: '<b>Pablo Larrán</b>, Madrid, Espagne. Esprit créatif développant des fantaisies musicales à travers des paysages sombres, des textures organiques et des atmosphères cinématographiques. Pulsation hypnotique du techno et profondeur immersive du progressive. Depuis 2018 consolidé avec des sorties sur Padang Records. <b>Festivals :</b> Own Spirit, Living Village, We Dark One. Actif dans la scène psychédélique espagnole comme artiste et organisateur d\'événements depuis 10+ ans. Sur Padang Records : <b>What?</b> (Technomad II, 05/2025), <b>Reminiscencias</b> (VA Nukaya, 05/2024) et <b>Orgelon</b>. Live avec Monkey Mind à Own Spirit 2023. Contact : musgolino.music@gmail.com.',
      ja: '<b>Pablo Larrán</b>、スペイン・マドリード出身。ダークな風景、オーガニックなテクスチャ、シネマティックなアトモスフィアを通して音楽的ファンタジーを生み出すクリエイティブな頭脳。テクノの催眠的なパルスとプログレッシブの没入的な深さが交差。2018年から Padang Records からの作品で活動を確立。<b>フェスティバル:</b> Own Spirit、Living Village、We Dark One。スペインのサイケデリックシーンでアーティストとイベントオーガナイザーとして10年以上活動。Padang Records から：<b>What?</b>（Technomad II、2025年5月）、<b>Reminiscencias</b>（VA Nukaya、2024年5月）、<b>Orgelon</b>。Own Spirit 2023 で Monkey Mind と共にライブ。連絡先: musgolino.music@gmail.com。'
    },

    "Myrtox": {
      en: 'Stuttgart, Germany. Also works as a professional mastering engineer (Mastering Bunker). On Padang Records: <b>Freak Show</b> (VA Nukaya), <b>EΛT MΛRBLΣZ</b> with MultiTul and <b>Abstract Evolution</b> with Mentor. Live @ U&D Festival in 2015.',
      es: 'Stuttgart, Alemania. También trabaja como mastering profesional (Mastering Bunker). En Padang Records: <b>Freak Show</b> (VA Nukaya), <b>EΛT MΛRBLΣZ</b> con MultiTul y <b>Abstract Evolution</b> con Mentor. Live @ U&D Festival en 2015.',
      de: 'Stuttgart, Deutschland. Arbeitet auch als professioneller Mastering-Engineer (Mastering Bunker). Auf Padang Records: <b>Freak Show</b> (VA Nukaya), <b>EΛT MΛRBLΣZ</b> mit MultiTul und <b>Abstract Evolution</b> mit Mentor. Live @ U&D Festival 2015.',
      fr: 'Stuttgart, Allemagne. Travaille également comme ingénieur de mastering professionnel (Mastering Bunker). Sur Padang Records : <b>Freak Show</b> (VA Nukaya), <b>EΛT MΛRBLΣZ</b> avec MultiTul et <b>Abstract Evolution</b> avec Mentor. Live @ U&D Festival en 2015.',
      ja: 'ドイツ・シュトゥットガルト。プロのマスタリング・エンジニアとしても活動（Mastering Bunker）。Padang Records から：<b>Freak Show</b>（VA Nukaya）、MultiTul と <b>EΛT MΛRBLΣZ</b>、Mentor と <b>Abstract Evolution</b>。2015年 U&D Festival でライブ。'
    },

    "Naias": {
      en: '<b>Official Padang Records DJane</b>, based in Lisbon. Performed at <b>Padang Lab Series EP.16</b> @ Omtara Festival. Range: minimal techno, Dark Prog, Forest and DarkPsy — a selection that stitches hypnotic layers to underground energy.',
      es: '<b>DJane oficial de Padang Records</b>, basada en Lisboa. Se presentó en <b>Padang Lab Series EP.16</b> @ Omtara Festival. Rango: minimal techno, Dark Prog, Forest y DarkPsy — selección que cose capas hipnóticas con energía underground.',
      de: '<b>Offizielle Padang-Records-DJane</b>, ansässig in Lissabon. Auftritt bei <b>Padang Lab Series EP.16</b> @ Omtara Festival. Spektrum: minimal techno, Dark Prog, Forest und DarkPsy — eine Auswahl, die hypnotische Schichten mit Underground-Energie zusammennäht.',
      fr: '<b>DJane officielle de Padang Records</b>, basée à Lisbonne. A joué à <b>Padang Lab Series EP.16</b> @ Omtara Festival. Spectre : minimal techno, Dark Prog, Forest et DarkPsy — une sélection qui coud des couches hypnotiques à l\\\'énergie underground.',
      ja: '<b>Padang Records 公式 DJane</b>、リスボン拠点。<b>Padang Lab Series EP.16</b> @ Omtara Festival に出演。レンジ：minimal techno、Dark Prog、Forest、DarkPsy — 催眠的なレイヤーとアンダーグラウンドのエネルギーを縫い合わせるセレクション。'
    },

    "Niobiun": {
      en: '<b>Josué Fernandes</b>, Brazil. <b>Dark Prog</b> project created in 2015 — sound influenced by techno, minimal, dark psy and <b>alternative metal</b>. Results in ambient, abstract progressive that travels between distinct musical variations and sonic experiments. Released the album <b>Intersections</b> on Padang Records (06/2021). Track <b>Universal Clock</b> (VA Exogenesis); collaborations <b>Space Artfact</b> and <b>Mind Echoes</b> with Orbsynth, both on Padang Records. Contact: josueb.fernandes@gmail.com.',
      es: '<b>Josué Fernandes</b>, Brasil. Proyecto de <b>Dark Prog</b> creado en 2015 — sonido influenciado por techno, minimal, dark psy y <b>metal alternativo</b>. Resulta en progresivo ambiente y abstracto que viaja entre distintas variaciones musicales y experimentos sonoros. Lanzó el álbum <b>Intersections</b> en Padang Records (06/2021). Track <b>Universal Clock</b> (VA Exogenesis); colaboraciones <b>Space Artfact</b> y <b>Mind Echoes</b> con Orbsynth, ambos en Padang Records. Contacto: josueb.fernandes@gmail.com.',
      de: '<b>Josué Fernandes</b>, Brasilien. <b>Dark-Prog</b>-Projekt 2015 ins Leben gerufen — der Sound von Techno, Minimal, Dark Psy und <b>Alternative Metal</b> beeinflusst. Ergibt ambient-progressive und abstrakte Musik, die sich zwischen verschiedenen musikalischen Variationen und klanglichen Experimenten bewegt. Veröffentlichte das Album <b>Intersections</b> auf Padang Records (06/2021). Track <b>Universal Clock</b> (VA Exogenesis); Kollaborationen <b>Space Artfact</b> und <b>Mind Echoes</b> mit Orbsynth, beide auf Padang Records. Kontakt: josueb.fernandes@gmail.com.',
      fr: '<b>Josué Fernandes</b>, Brésil. Projet <b>Dark Prog</b> créé en 2015 — son influencé par le techno, le minimal, le dark psy et le <b>métal alternatif</b>. Aboutit à un progressive ambient et abstrait qui voyage entre des variations musicales distinctes et des expériences sonores. A sorti l\'album <b>Intersections</b> sur Padang Records (06/2021). Morceau <b>Universal Clock</b> (VA Exogenesis); collaborations <b>Space Artfact</b> et <b>Mind Echoes</b> avec Orbsynth, toutes deux sur Padang Records. Contact : josueb.fernandes@gmail.com.',
      ja: '<b>Josué Fernandes</b>、ブラジル出身。2015年に立ち上げた <b>Dark Prog</b> プロジェクト — テクノ、ミニマル、ダークサイ、<b>オルタナティブメタル</b> の影響を受けたサウンド。様々な音楽的バリエーションとサウンド実験を行き来する、アンビエント＆アブストラクトなプログレッシブを生み出す。Padang Records からアルバム <b>Intersections</b>（2021年6月）をリリース。<b>Universal Clock</b>（VA Exogenesis）、Orbsynth との共作 <b>Space Artfact</b>、<b>Mind Echoes</b>（共に Padang Records）。連絡先: josueb.fernandes@gmail.com。'
    },

    "Nuit Noire": {
      en: 'Christina. Queer DJ based in Montréal, Canada — <b>Padang Records label DJ</b>. Mixes techno, dark prog and psytech. Curated <b>VA The Nightmare</b> (08/2025) on Padang Records — a journey where frightening memories and pleasure collide. Recent sets: Sanctuary 2025 (Bain Mathieu, Montreal), Arkana showcase Montréal 2025 and Era Festival 2024.',
      es: 'Christina. Queer DJ basada en Montreal, Canadá — <b>label DJ de Padang Records</b>. Mezcla techno, dark prog y psytech. Curó <b>VA The Nightmare</b> (08/2025) en Padang Records — un viaje donde memorias aterradoras y placer colisionan. Sets recientes: Sanctuary 2025 (Bain Mathieu, Montreal), Arkana showcase Montréal 2025 y Era Festival 2024.',
      de: 'Christina. Queere DJ in Montréal, Kanada — <b>Padang-Records-Label-DJ</b>. Mischt Techno, Dark Prog und Psytech. Kuratierte <b>VA The Nightmare</b> (08/2025) auf Padang Records — eine Reise, in der erschreckende Erinnerungen und Lust kollidieren. Aktuelle Sets: Sanctuary 2025 (Bain Mathieu, Montreal), Arkana Showcase Montréal 2025 und Era Festival 2024.',
      fr: 'Christina. DJ queer basée à Montréal, Canada — <b>label DJ de Padang Records</b>. Mélange techno, dark prog et psytech. A curaté <b>VA The Nightmare</b> (08/2025) sur Padang Records — un voyage où mémoires effrayantes et plaisir entrent en collision. Sets récents : Sanctuary 2025 (Bain Mathieu, Montréal), Arkana showcase Montréal 2025 et Era Festival 2024.',
      ja: 'Christina。カナダ・モントリオール拠点のクィア DJ — <b>Padang Records レーベル DJ</b>。Techno、Dark Prog、Psytech をミックス。Padang Records で <b>VA The Nightmare</b>（2025年8月）をキュレーション — 恐ろしい記憶と快楽が衝突する旅。最近のセット：Sanctuary 2025（Bain Mathieu、モントリオール）、Arkana showcase Montréal 2025、Era Festival 2024。'
    },

    "Orbsynth": {
      en: 'Brazilian artist associated with <b>Padang Records</b>. Collaborations with Niobiun on <b>Space Artfact</b> and <b>Mind Echoes</b> (both on Padang). Psy-trance / dark progressive.',
      es: 'Artista brasileño asociado a <b>Padang Records</b>. Colaboraciones con Niobiun en <b>Space Artfact</b> y <b>Mind Echoes</b> (ambos en Padang). Psy-trance / dark progressive.',
      de: 'Brasilianischer Künstler bei <b>Padang Records</b>. Kollaborationen mit Niobiun bei <b>Space Artfact</b> und <b>Mind Echoes</b> (beide auf Padang). Psy-Trance / Dark Progressive.',
      fr: 'Artiste brésilien associé à <b>Padang Records</b>. Collaborations avec Niobiun sur <b>Space Artfact</b> et <b>Mind Echoes</b> (toutes deux sur Padang). Psy-trance / dark progressive.',
      ja: '<b>Padang Records</b> 所属のブラジル人アーティスト。Niobiun と <b>Space Artfact</b> および <b>Mind Echoes</b>（ともに Padang）でコラボ。Psy-trance ／ Dark Progressive。'
    },

    "Paracozm": {
      en: '<b>Diego Brinker</b>, southern Brazil. Defined as a meticulously crafted imaginary realm of fantasy, originating within the confines of cognition itself. Deep, enigmatic, velvety and visionary soundscapes. <b>On Padang Records:</b> <b>Packet Loss</b> (11/2019), <b>Paracozm Redux</b> (06/2016); remixes Hellquist (Northern Night) and Pspiralife (Liquid Nails); track <b>Oni</b> on VA Reborn. <b>Festivals:</b> Earthdance RS, Flux Indoor.',
      es: '<b>Diego Brinker</b>, sur de Brasil. Definido como un reino imaginario meticulosamente construido de fantasía, originado dentro de los confines de la propia cognición. Soundscapes profundos, enigmáticos, aterciopelados y visionarios. <b>En Padang Records:</b> <b>Packet Loss</b> (11/2019), <b>Paracozm Redux</b> (06/2016); remixes Hellquist (Northern Night) y Pspiralife (Liquid Nails); track <b>Oni</b> en VA Reborn. <b>Festivales:</b> Earthdance RS, Flux Indoor.',
      de: '<b>Diego Brinker</b>, Südbrasilien. Definiert als ein akribisch konstruiertes Reich der Fantasie, das aus den Grenzen der Wahrnehmung selbst entsteht. Tiefe, rätselhafte, samtige und visionäre Soundscapes. <b>Auf Padang Records:</b> <b>Packet Loss</b> (11/2019), <b>Paracozm Redux</b> (06/2016); Remixe Hellquist (Northern Night) und Pspiralife (Liquid Nails); Track <b>Oni</b> auf VA Reborn. <b>Festivals:</b> Earthdance RS, Flux Indoor.',
      fr: '<b>Diego Brinker</b>, sud du Brésil. Défini comme un royaume imaginaire de fantaisie minutieusement construit, né dans les limites de la cognition elle-même. Soundscapes profonds, énigmatiques, veloutés et visionnaires. <b>Sur Padang Records :</b> <b>Packet Loss</b> (11/2019), <b>Paracozm Redux</b> (06/2016); remix Hellquist (Northern Night) et Pspiralife (Liquid Nails); morceau <b>Oni</b> sur VA Reborn. <b>Festivals :</b> Earthdance RS, Flux Indoor.',
      ja: '<b>Diego Brinker</b>、ブラジル南部出身。認知そのものの境界の中から立ち上がる、緻密に構築された幻想の王国として定義される。深く、謎めき、ベルベットのような視覚的サウンドスケープ。<b>Padang Records から：</b><b>Packet Loss</b>（2019年11月）、<b>Paracozm Redux</b>（2016年6月）；リミックス Hellquist（Northern Night）、Pspiralife（Liquid Nails）；VA Reborn に <b>Oni</b>。<b>フェス：</b>Earthdance RS、Flux Indoor。'
    },

    "Psydewise": {
      en: '<b>Sam Gamgee</b>, Garden Route, South Africa. "Music producer, merry prankster". Styles: Psytrance, Zenonesque, Dark Progressive. Debut <b>Dirty Wizards</b> — a dark and groovy tech-meets-progressive blend. EP <b>Mandelbrot Sequence</b> on Padang Records. Hanging Gardens (WIP) collab with Camps Elisis. Contact: psydewise@gmail.com.',
      es: '<b>Sam Gamgee</b>, Garden Route, Sudáfrica. "Music producer, merry prankster". Estilos: Psytrance, Zenonesque, Dark Progressive. Debut <b>Dirty Wizards</b> — blend dark y groovy de tech y progressive. EP <b>Mandelbrot Sequence</b> en Padang Records. Colab Hanging Gardens (WIP) con Camps Elisis. Contacto: psydewise@gmail.com.',
      de: '<b>Sam Gamgee</b>, Garden Route, Südafrika. "Music producer, merry prankster". Stile: Psytrance, Zenonesque, Dark Progressive. Debüt <b>Dirty Wizards</b> — düstere und groovige Tech-meets-Progressive-Mischung. EP <b>Mandelbrot Sequence</b> auf Padang Records. Hanging-Gardens-Kollab (WIP) mit Camps Elisis. Kontakt: psydewise@gmail.com.',
      fr: '<b>Sam Gamgee</b>, Garden Route, Afrique du Sud. « Music producer, merry prankster ». Styles : Psytrance, Zenonesque, Dark Progressive. Premier <b>Dirty Wizards</b> — mélange dark et groovy de tech et progressive. EP <b>Mandelbrot Sequence</b> sur Padang Records. Collab Hanging Gardens (WIP) avec Camps Elisis. Contact : psydewise@gmail.com.',
      ja: '<b>Sam Gamgee</b>、南アフリカ・ガーデンルート出身。「Music producer, merry prankster」。スタイル：Psytrance、Zenonesque、Dark Progressive。デビュー <b>Dirty Wizards</b> — ダークでグルーヴィーな tech ＋ progressive のブレンド。Padang Records から EP <b>Mandelbrot Sequence</b>。Camps Elisis と Hanging Gardens（制作中）でコラボ。連絡先: psydewise@gmail.com。'
    },

    "Rhabia": {
      en: '<b>Lena (Rhabia)</b>, Germany. DJ, singer and producer — "hybrids". "Boundless alchemist of genrefluid sound & emotion". Styles: Psytech, Dark- & Bushprog, Zenonesque, Breaks, DnB, deep hypnotic & primal techno. <b>Festivals:</b> <b>Modem Festival</b> (Croatia), <b>Bucht der Träumer</b>, <b>Fusion</b>, <b>Hadra Trance</b>, <b>Antaris</b>, <b>Hive</b>. Curated <b>VA Nyctophilia</b> (Padang Records, 02/2025) — included the track <b>Amante Oscuro</b> with DMnT and Semilocybe.',
      es: '<b>Lena (Rhabia)</b>, Alemania. DJ, cantante y productora — "hybrids". "Boundless alchemist of genrefluid sound & emotion". Estilos: Psytech, Dark- & Bushprog, Zenonesque, Breaks, DnB, deep hypnotic & primal techno. <b>Festivales:</b> <b>Modem Festival</b> (Croacia), <b>Bucht der Träumer</b>, <b>Fusion</b>, <b>Hadra Trance</b>, <b>Antaris</b>, <b>Hive</b>. Curó <b>VA Nyctophilia</b> (Padang Records, 02/2025) — incluyó el track <b>Amante Oscuro</b> con DMnT y Semilocybe.',
      de: '<b>Lena (Rhabia)</b>, Deutschland. DJ, Sängerin und Produzentin — "hybrids". "Boundless alchemist of genrefluid sound & emotion". Stile: Psytech, Dark- & Bushprog, Zenonesque, Breaks, DnB, deep hypnotic & primal techno. <b>Festivals:</b> <b>Modem Festival</b> (Kroatien), <b>Bucht der Träumer</b>, <b>Fusion</b>, <b>Hadra Trance</b>, <b>Antaris</b>, <b>Hive</b>. Kuratierte <b>VA Nyctophilia</b> (Padang Records, 02/2025) — mit dem Track <b>Amante Oscuro</b> zusammen mit DMnT und Semilocybe.',
      fr: '<b>Lena (Rhabia)</b>, Allemagne. DJ, chanteuse et productrice — « hybrids ». « Boundless alchemist of genrefluid sound & emotion ». Styles : Psytech, Dark- & Bushprog, Zenonesque, Breaks, DnB, deep hypnotic & primal techno. <b>Festivals :</b> <b>Modem Festival</b> (Croatie), <b>Bucht der Träumer</b>, <b>Fusion</b>, <b>Hadra Trance</b>, <b>Antaris</b>, <b>Hive</b>. A curaté <b>VA Nyctophilia</b> (Padang Records, 02/2025) — incluant le morceau <b>Amante Oscuro</b> avec DMnT et Semilocybe.',
      ja: '<b>Lena (Rhabia)</b>、ドイツ出身。DJ／シンガー／プロデューサー — 「hybrids」。「Boundless alchemist of genrefluid sound & emotion」。スタイル：Psytech、Dark- & Bushprog、Zenonesque、Breaks、DnB、deep hypnotic & primal techno。<b>フェス：</b><b>Modem Festival</b>（クロアチア）、<b>Bucht der Träumer</b>、<b>Fusion</b>、<b>Hadra Trance</b>、<b>Antaris</b>、<b>Hive</b>。Padang Records で <b>VA Nyctophilia</b>（2025年2月）をキュレーション — DMnT と Semilocybe との <b>Amante Oscuro</b> を収録。'
    },

    "Ritalin Child": {
      en: 'DJ/producer from Córdoba, Argentina. Hypnotic psychedelic trance, dark atmospheres, insane basslines. On Padang Records: <b>The Awakening EP</b>, <b>Attention Deficit</b> (VA Exogenesis), <b>Control This...</b> (VA Haunted Spectre 2) and <b>Blue Beam Project</b>. Maintains a Padang Records playlist on SoundCloud.',
      es: 'DJ/productor de Córdoba, Argentina. Trance psicodélico hipnótico, atmósferas oscuras, basslines insanos. En Padang Records: <b>The Awakening EP</b>, <b>Attention Deficit</b> (VA Exogenesis), <b>Control This...</b> (VA Haunted Spectre 2) y <b>Blue Beam Project</b>. Mantiene playlist Padang Records en SoundCloud.',
      de: 'DJ/Produzent aus Córdoba, Argentinien. Hypnotischer psychedelischer Trance, düstere Atmosphären, wahnsinnige Basslines. Auf Padang Records: <b>The Awakening EP</b>, <b>Attention Deficit</b> (VA Exogenesis), <b>Control This...</b> (VA Haunted Spectre 2) und <b>Blue Beam Project</b>. Pflegt eine Padang-Records-Playlist auf SoundCloud.',
      fr: 'DJ/producteur de Córdoba, Argentine. Trance psychédélique hypnotique, atmosphères sombres, basses délirantes. Sur Padang Records : <b>The Awakening EP</b>, <b>Attention Deficit</b> (VA Exogenesis), <b>Control This...</b> (VA Haunted Spectre 2) et <b>Blue Beam Project</b>. Tient une playlist Padang Records sur SoundCloud.',
      ja: 'アルゼンチン・コルドバ出身の DJ／プロデューサー。催眠的なサイケデリック・トランス、ダークなアトモスフィア、狂気じみたベースライン。Padang Records から：<b>The Awakening EP</b>、<b>Attention Deficit</b>（VA Exogenesis）、<b>Control This...</b>（VA Haunted Spectre 2）、<b>Blue Beam Project</b>。SoundCloud で Padang Records プレイリストを運営。'
    },

    "Rollercoaster": {
      en: '<b>Gabriel Gómez</b> — Chile, born in Concepción (cradle of Chilean rock). Studied jazz and electric bass before moving into electronics. Aliases: <b>Rollercoaster / Paracoaster / Arcturians / Gao / Kilbee</b>. 15+ years producing electronic music. On Padang Records: <b>Brake the Chains</b> (25/12/2024) — 3 tracks (New Beginning, Brake the Chains, Is Not Real) and <b>Volcano</b> collab with Paracozm. Sets on 5 continents.',
      es: '<b>Gabriel Gómez</b> — Chile, nacido en Concepción (cuna del rock chileno). Estudió jazz y bajo eléctrico antes de migrar a la electrónica. Alias: <b>Rollercoaster / Paracoaster / Arcturians / Gao / Kilbee</b>. 15+ años produciendo electrónica. En Padang Records: <b>Brake the Chains</b> (25/12/2024) — 3 tracks (New Beginning, Brake the Chains, Is Not Real) y colab <b>Volcano</b> con Paracozm. Sets en 5 continentes.',
      de: '<b>Gabriel Gómez</b> — Chile, geboren in Concepción (Wiege des chilenischen Rock). Studierte Jazz und E-Bass, bevor er in die Elektronik wechselte. Aliase: <b>Rollercoaster / Paracoaster / Arcturians / Gao / Kilbee</b>. 15+ Jahre als elektronischer Produzent. Auf Padang Records: <b>Brake the Chains</b> (25.12.2024) — 3 Tracks (New Beginning, Brake the Chains, Is Not Real) und <b>Volcano</b>-Kollab mit Paracozm. Sets auf 5 Kontinenten.',
      fr: '<b>Gabriel Gómez</b> — Chili, né à Concepción (berceau du rock chilien). A étudié le jazz et la basse électrique avant de basculer vers l\\\'électronique. Alias : <b>Rollercoaster / Paracoaster / Arcturians / Gao / Kilbee</b>. 15+ ans de production électronique. Sur Padang Records : <b>Brake the Chains</b> (25/12/2024) — 3 morceaux (New Beginning, Brake the Chains, Is Not Real) et collab <b>Volcano</b> avec Paracozm. Sets sur 5 continents.',
      ja: '<b>Gabriel Gómez</b> — チリ、コンセプシオン（チリ・ロックの揺りかご）生まれ。ジャズとエレキベースを学んだのちエレクトロニクスへ移行。エイリアス：<b>Rollercoaster／Paracoaster／Arcturians／Gao／Kilbee</b>。15年以上にわたる電子音楽制作。Padang Records から：<b>Brake the Chains</b>（2024年12月25日） — 3トラック（New Beginning、Brake the Chains、Is Not Real）と Paracozm との <b>Volcano</b> コラボ。5大陸でセット。'
    },

    "Ronaldo Noctusense": {
      en: '<b>Ronaldo Lindote</b>, Bahia, Brazil. DJ and compiler for <b>Padang Records</b>. Curated the <b>VA Haunted Spectre 1-4</b> series (Padang Records, 2016-2024) — gathering tracks from friends around the world in a freaky fusion of psychedelic, experimental and avant-garde.',
      es: '<b>Ronaldo Lindote</b>, Bahía, Brasil. DJ y compilador de <b>Padang Records</b>. Curó la serie <b>VA Haunted Spectre 1-4</b> (Padang Records, 2016-2024) — reuniendo tracks de amigos por todo el mundo en una freaky fusion de psicodélico, experimental y avant-garde.',
      de: '<b>Ronaldo Lindote</b>, Bahia, Brasilien. DJ und Compiler bei <b>Padang Records</b>. Kuratierte die Reihe <b>VA Haunted Spectre 1-4</b> (Padang Records, 2016-2024) — sammelte Tracks von Freunden weltweit in einer freaky Fusion aus Psychedelisch, Experimentell und Avantgarde.',
      fr: '<b>Ronaldo Lindote</b>, Bahia, Brésil. DJ et compilateur pour <b>Padang Records</b>. A curaté la série <b>VA Haunted Spectre 1-4</b> (Padang Records, 2016-2024) — rassemblant des morceaux d\\\'amis du monde entier dans une freaky fusion de psychédélique, expérimental et avant-garde.',
      ja: '<b>Ronaldo Lindote</b>、ブラジル・バイーア出身。<b>Padang Records</b> の DJ／コンパイラー。<b>VA Haunted Spectre 1-4</b> シリーズ（Padang Records、2016-2024）をキュレーション — 世界中の友人のトラックを集め、サイケデリック・実験的・アヴァンギャルドが入り混じる freaky なフュージョンに。'
    },

    "Runehk": {
      en: '<b>Hernán Llanos</b>, born in <b>El Bolsón (Argentine Patagonia) in 1984</b>. In Buenos Aires since 2005, self-taught starting with minimal and techno foundations before enrolling in a production institute. In 2018 launched the "Runehk" project — psychedelia with techno nuances, powerful basslines and energetic, characterful lead sounds. <b>First international performance: Arkana Festival 2025 (Peru)</b>. On Padang Records: <b>Broken Mind (24bit)</b> album (12/2022 — Broken Mind, Dark Code, Space Explorer), <b>Revolution</b> and track <b>Dolor de Mazo</b> (Technomad II, 05/2025). Also known as Avantrash.',
      es: '<b>Hernán Llanos</b>, nacido en <b>El Bolsón (Patagonia Argentina) en 1984</b>. En Buenos Aires desde 2005, autodidacta comenzando con fundamentos de minimal y techno antes de entrar a un instituto de producción. En 2018 lanzó el proyecto "Runehk" — psicodelia con matices techno, basslines potentes y sonidos lead enérgicos y característicos. <b>Primera performance internacional: Arkana Festival 2025 (Perú)</b>. En Padang Records: álbum <b>Broken Mind (24bit)</b> (12/2022 — Broken Mind, Dark Code, Space Explorer), <b>Revolution</b> y track <b>Dolor de Mazo</b> (Technomad II, 05/2025). También conocido como Avantrash.',
      de: '<b>Hernán Llanos</b>, geboren in <b>El Bolsón (argentinisches Patagonien) 1984</b>. Lebt seit 2005 in Buenos Aires, autodidaktisch begann mit Minimal- und Techno-Grundlagen, bevor er an einem Produktionsinstitut studierte. 2018 startete er das Projekt "Runehk" — Psychedelia mit Techno-Nuancen, kraftvollen Basslines und energetischen, charaktervollen Lead-Sounds. <b>Erster internationaler Auftritt: Arkana Festival 2025 (Peru)</b>. Auf Padang Records: Album <b>Broken Mind (24bit)</b> (12/2022 — Broken Mind, Dark Code, Space Explorer), <b>Revolution</b> und Track <b>Dolor de Mazo</b> (Technomad II, 05/2025). Auch bekannt als Avantrash.',
      fr: '<b>Hernán Llanos</b>, né à <b>El Bolsón (Patagonie argentine) en 1984</b>. À Buenos Aires depuis 2005, autodidacte ayant débuté avec les fondations du minimal et du techno avant d\'intégrer un institut de production. En 2018 lance le projet "Runehk" — psychédélie aux nuances techno, basslines puissantes et leads énergiques et caractérisés. <b>Première performance internationale : Arkana Festival 2025 (Pérou)</b>. Sur Padang Records : album <b>Broken Mind (24bit)</b> (12/2022 — Broken Mind, Dark Code, Space Explorer), <b>Revolution</b> et morceau <b>Dolor de Mazo</b> (Technomad II, 05/2025). Aussi connu sous le nom d\'Avantrash.',
      ja: '<b>Hernán Llanos</b>、<b>1984年にアルゼンチン・パタゴニアのエル・ボルソンで生まれる</b>。2005年からブエノスアイレス在住、ミニマルとテクノの基礎から独学で始め、その後プロダクションの専門学校に入学。2018年に「Runehk」プロジェクトを立ち上げ — テクノのニュアンス、力強いベースライン、エネルギッシュで個性的なリードサウンドを持つサイケデリア。<b>初の国際公演: Arkana Festival 2025（ペルー）</b>。Padang Records から：アルバム <b>Broken Mind (24bit)</b>（2022年12月 — Broken Mind、Dark Code、Space Explorer）、<b>Revolution</b>、トラック <b>Dolor de Mazo</b>（Technomad II、2025年5月）。Avantrash としても知られる。'
    },

    "Secular Bonzo": {
      en: '<b>Franco Schneider and Augusto Comoretto</b>, southern Brazil. Dark Progressive project created by two friends to explore the low frequencies of electronic music. Forest and Psytrance influences integrate technology with beats into a unique immersive sound. On Padang Records: album <b>Dual Nature</b> (09/2023). Contact: secularbonzo@gmail.com.',
      es: '<b>Franco Schneider y Augusto Comoretto</b>, sur de Brasil. Proyecto Dark Progressive creado por dos amigos para explorar las frecuencias graves de la electrónica. Influencias Forest y Psytrance integran tecnología con beats en un sonido inmersivo único. En Padang Records: álbum <b>Dual Nature</b> (09/2023). Contacto: secularbonzo@gmail.com.',
      de: '<b>Franco Schneider und Augusto Comoretto</b>, Südbrasilien. Dark-Progressive-Projekt zweier Freunde zur Erforschung der tiefen Frequenzen elektronischer Musik. Forest- und Psytrance-Einflüsse verschmelzen Technologie und Beats zu einem einzigartigen, immersiven Sound. Auf Padang Records: Album <b>Dual Nature</b> (09/2023). Kontakt: secularbonzo@gmail.com.',
      fr: '<b>Franco Schneider et Augusto Comoretto</b>, sud du Brésil. Projet Dark Progressive créé par deux amis pour explorer les fréquences graves de la musique électronique. Des influences Forest et Psytrance intègrent la technologie aux beats dans un son immersif unique. Sur Padang Records : album <b>Dual Nature</b> (09/2023). Contact : secularbonzo@gmail.com.',
      ja: '<b>Franco Schneider と Augusto Comoretto</b>、ブラジル南部。エレクトロニック音楽の低周波数帯を探求するために 2 人の友人が立ち上げた Dark Progressive プロジェクト。Forest と Psytrance の影響が技術とビートを融合させ、独自の没入的サウンドを生む。Padang Records からアルバム <b>Dual Nature</b>（2023年9月）。連絡先: secularbonzo@gmail.com。'
    },

    "Smokcid": {
      en: '<b>Themis Dirlis</b>, Greece. Explores dark and atmospheric realms through minimalist compositions emphasizing simplicity and depth. <b>Zenonesque</b> and Dark Progressive aesthetics — organic textures with modular synthesizers, immersive evolving soundscapes. Debut EP <b>SPIRAL FORM</b>. On Padang Records: <b>Phazer</b> (VA Exogenesis 2017), <b>Portal Space</b> and collaboration <b>Noctura</b> with Headweller (VA Nyctophilia). Contact: dirlisd@gmail.com.',
      es: '<b>Themis Dirlis</b>, Grecia. Explora dominios oscuros y atmosféricos a través de composiciones minimalistas que enfatizan simplicidad y profundidad. Estética <b>Zenonesque</b> y Dark Progressive — texturas orgánicas con sintetizadores modulares, paisajes sonoros inmersivos en evolución. EP debut <b>SPIRAL FORM</b>. En Padang Records: <b>Phazer</b> (VA Exogenesis 2017), <b>Portal Space</b> y colaboración <b>Noctura</b> con Headweller (VA Nyctophilia). Contacto: dirlisd@gmail.com.',
      de: '<b>Themis Dirlis</b>, Griechenland. Erforscht düstere und atmosphärische Sphären durch minimalistische Kompositionen, die Einfachheit und Tiefe betonen. <b>Zenonesque</b>- und Dark-Progressive-Ästhetik — organische Texturen mit modularen Synthesizern, immersive sich entwickelnde Klanglandschaften. Debüt-EP <b>SPIRAL FORM</b>. Auf Padang Records: <b>Phazer</b> (VA Exogenesis 2017), <b>Portal Space</b> und Kollaboration <b>Noctura</b> mit Headweller (VA Nyctophilia). Kontakt: dirlisd@gmail.com.',
      fr: '<b>Themis Dirlis</b>, Grèce. Explore les sphères sombres et atmosphériques à travers des compositions minimalistes mettant l\'accent sur la simplicité et la profondeur. Esthétique <b>Zenonesque</b> et Dark Progressive — textures organiques avec synthétiseurs modulaires, paysages sonores immersifs en évolution. EP de début <b>SPIRAL FORM</b>. Sur Padang Records : <b>Phazer</b> (VA Exogenesis 2017), <b>Portal Space</b> et collaboration <b>Noctura</b> avec Headweller (VA Nyctophilia). Contact : dirlisd@gmail.com.',
      ja: '<b>Themis Dirlis</b>、ギリシャ出身。シンプルさと深みを強調するミニマリスト的なコンポジションを通してダークでアトモスフェリックな領域を探求。<b>Zenonesque</b> と Dark Progressive の美学 — モジュラーシンセサイザーによるオーガニックなテクスチャと、没入的に進化するサウンドスケープ。デビュー EP <b>SPIRAL FORM</b>。Padang Records から：<b>Phazer</b>（VA Exogenesis 2017）、<b>Portal Space</b>、Headweller との共作 <b>Noctura</b>（VA Nyctophilia）。連絡先: dirlisd@gmail.com。'
    },

    "Stix": {
      en: '<b>Deepy Sidhu</b>, Winnipeg, Canada. "Colouring outside the lines of dark tech". Producer and DJ of dark electronic music — hypnotic fusion of psytrance, psytech, techno, house and bass. Curated <b>VA Yin and Yang Studio Gang</b> on Padang Records (16/01/2025) — a celebration of light/dark, chaos/harmony duality. Contact: sidhudeepy@gmail.com.',
      es: '<b>Deepy Sidhu</b>, Winnipeg, Canadá. "Colouring outside the lines of dark tech". Productora y DJ de electrónica dark — fusión hipnótica de psytrance, psytech, techno, house y bass. Curó en Padang Records la <b>VA Yin and Yang Studio Gang</b> (16/01/2025) — celebración de dualidad luz/sombra, caos/armonía. Contacto: sidhudeepy@gmail.com.',
      de: '<b>Deepy Sidhu</b>, Winnipeg, Kanada. "Colouring outside the lines of dark tech". Produzentin und DJ dunkler elektronischer Musik — hypnotische Fusion aus Psytrance, Psytech, Techno, House und Bass. Kuratierte auf Padang Records die <b>VA Yin and Yang Studio Gang</b> (16.01.2025) — eine Feier der Dualität Licht/Dunkel, Chaos/Harmonie. Kontakt: sidhudeepy@gmail.com.',
      fr: '<b>Deepy Sidhu</b>, Winnipeg, Canada. « Colouring outside the lines of dark tech ». Productrice et DJ d\\\'électronique dark — fusion hypnotique de psytrance, psytech, techno, house et bass. A curaté sur Padang Records la <b>VA Yin and Yang Studio Gang</b> (16/01/2025) — célébration de la dualité lumière/ombre, chaos/harmonie. Contact : sidhudeepy@gmail.com.',
      ja: '<b>Deepy Sidhu</b>、カナダ・ウィニペグ出身。「Colouring outside the lines of dark tech」。dark エレクトロニックのプロデューサー／DJ — psytrance、psytech、techno、house、bass の催眠的なフュージョン。Padang Records で <b>VA Yin and Yang Studio Gang</b>（2025年1月16日）をキュレーション — 光／闇、混沌／調和の二元性を祝う。連絡先: sidhudeepy@gmail.com。'
    },

    "Stopless": {
      en: '<b>Aldi Castori</b>, born in Mexico, lives in Pachuca. After 10 years in grunge/rock/indie bands on guitar, bass and drums, in 2009 he moved into IDM, experimental and psytrance. On Padang Records he released <b>Synchromisticism</b> and the track <b>Stone Cutters</b>. Collaborated with Jungle Haze on the <b>Technochtitlan EP</b> in 2018.',
      es: '<b>Aldi Castori</b>, nacido en México, vive en Pachuca. Tras 10 años en bandas de grunge/rock/indie tocando guitarra, bajo y batería, en 2009 migró a IDM, experimental y psytrance. En Padang Records lanzó <b>Synchromisticism</b> y el track <b>Stone Cutters</b>. Colaboró con Jungle Haze en el <b>Technochtitlan EP</b> en 2018.',
      de: '<b>Aldi Castori</b>, geboren in Mexiko, lebt in Pachuca. Nach 10 Jahren in Grunge-/Rock-/Indie-Bands an Gitarre, Bass und Schlagzeug wechselte er 2009 zu IDM, Experimental und Psytrance. Auf Padang Records veröffentlichte er <b>Synchromisticism</b> und den Track <b>Stone Cutters</b>. Kollaboration mit Jungle Haze auf der <b>Technochtitlan EP</b> 2018.',
      fr: '<b>Aldi Castori</b>, né au Mexique, vit à Pachuca. Après 10 ans dans des groupes grunge/rock/indie à la guitare, basse et batterie, il bascule en 2009 vers l\\\'IDM, l\\\'expérimental et le psytrance. Sur Padang Records il a sorti <b>Synchromisticism</b> et le morceau <b>Stone Cutters</b>. A collaboré avec Jungle Haze sur le <b>Technochtitlan EP</b> en 2018.',
      ja: '<b>Aldi Castori</b>、メキシコ生まれ、パチューカ在住。grunge／rock／indie バンドでギター、ベース、ドラムを 10 年プレイしたのち、2009年に IDM、実験的音楽、psytrance へ移行。Padang Records から <b>Synchromisticism</b> と楽曲 <b>Stone Cutters</b> をリリース。2018年に Jungle Haze と <b>Technochtitlan EP</b> でコラボ。'
    },

    "Sumerian Droids": {
      en: '<b>Pioneer of Dark Progressive</b> in Chile and worldwide, in the original Zenon style. Explores Swap Progressive, Minimalistic, Glitch, Techno and Psychedelic Progressive (120-142 BPM). Started as the duo Diego + Gabriel; today a solo project of <b>Gabriel (Josh Live, Cryptophonix)</b> from Santiago. On Padang Records: track <b>Brahmasutra</b>. <b>Festivals:</b> 3 Dimensions Festival (live set 2022).',
      es: '<b>Pionero del Dark Progressive</b> en Chile y el mundo, en el estilo original Zenon. Explora Swap Progressive, Minimalistic, Glitch, Techno y Psychedelic Progressive (120-142 BPM). Empezó como dúo Diego + Gabriel; hoy es proyecto solo de <b>Gabriel (Josh Live, Cryptophonix)</b> de Santiago. En Padang Records: track <b>Brahmasutra</b>. <b>Festivales:</b> 3 Dimensions Festival (live set 2022).',
      de: '<b>Pionier des Dark Progressive</b> in Chile und weltweit, im Original-Zenon-Stil. Erforscht Swap Progressive, Minimalistic, Glitch, Techno und Psychedelic Progressive (120-142 BPM). Begann als Duo Diego + Gabriel; heute ein Solo-Projekt von <b>Gabriel (Josh Live, Cryptophonix)</b> aus Santiago. Auf Padang Records: Track <b>Brahmasutra</b>. <b>Festivals:</b> 3 Dimensions Festival (Live-Set 2022).',
      fr: '<b>Pionnier du Dark Progressive</b> au Chili et dans le monde, dans le style original Zenon. Explore Swap Progressive, Minimalistic, Glitch, Techno et Psychedelic Progressive (120-142 BPM). Démarré en duo Diego + Gabriel; aujourd\'hui projet solo de <b>Gabriel (Josh Live, Cryptophonix)</b> de Santiago. Sur Padang Records : morceau <b>Brahmasutra</b>. <b>Festivals :</b> 3 Dimensions Festival (live set 2022).',
      ja: 'チリと世界における <b>Dark Progressive の先駆者</b>、オリジナルの Zenon スタイル。Swap Progressive、Minimalistic、Glitch、Forest、Techno、Psychedelic Progressive（120-142 BPM）を探求。Diego ＋ Gabriel のデュオとして始まり、現在はサンティアゴの <b>Gabriel（Josh Live、Cryptophonix）</b> のソロ・プロジェクト。Padang Records から楽曲 <b>Brahmasutra</b>。<b>フェス：</b>3 Dimensions Festival（2022年ライブセット）。'
    },

    "Sundenbock & Maddizin": {
      en: 'Freiburg, Germany. Duo formed in 2012 — creative union of two long-time friends. Styles: Zenonesque, Techtrance and Darkprog. On Padang Records: <b>Flying Zoo</b> (02/2026), <b>Neurovers</b>, <b>Sonos Aureus</b> (live mix), <b>Salt & Suger</b> and <b>Synonym</b>. A trip from Techno + Minimal to the psychedelic, on the border between Techno and Psy.',
      es: 'Friburgo, Alemania. Dúo nacido en 2012 — unión creativa de dos amigos de toda la vida. Estilos: Zenonesque, Techtrance y Darkprog. En Padang Records: <b>Flying Zoo</b> (02/2026), <b>Neurovers</b>, <b>Sonos Aureus</b> (live mix), <b>Salt & Suger</b> y <b>Synonym</b>. Viaje de Techno + Minimal a lo psicodélico, frontera entre Techno y Psy.',
      de: 'Freiburg, Deutschland. Duo gegründet 2012 — kreative Verbindung zweier langjähriger Freunde. Stile: Zenonesque, Techtrance und Darkprog. Auf Padang Records: <b>Flying Zoo</b> (02/2026), <b>Neurovers</b>, <b>Sonos Aureus</b> (Live-Mix), <b>Salt & Suger</b> und <b>Synonym</b>. Eine Reise von Techno + Minimal ins Psychedelische, an der Grenze zwischen Techno und Psy.',
      fr: 'Fribourg, Allemagne. Duo formé en 2012 — union créative de deux amis de longue date. Styles : Zenonesque, Techtrance et Darkprog. Sur Padang Records : <b>Flying Zoo</b> (02/2026), <b>Neurovers</b>, <b>Sonos Aureus</b> (live mix), <b>Salt & Suger</b> et <b>Synonym</b>. Un voyage de Techno + Minimal vers le psychédélique, à la frontière entre Techno et Psy.',
      ja: 'ドイツ・フライブルク。2012 年に結成されたデュオ — 長年の友人 2 人による創造的な結合。スタイル：Zenonesque、Techtrance、Darkprog。Padang Records から：<b>Flying Zoo</b>（2026年2月）、<b>Neurovers</b>、<b>Sonos Aureus</b>（ライブミックス）、<b>Salt & Suger</b>、<b>Synonym</b>。Techno + Minimal からサイケデリックへ、Techno と Psy の境界をたどる旅。'
    },

    "Symetric": {
      en: '<b>Symetric Live</b>, São Paulo, Brazil. Live act combining production precision with dancefloor energy. On Padang Records: <b>Alchemy Circle - RJ 2.0</b> remix and <b>Digital Forest</b> with Soulid (VA Padang × Noctusense). Performed live at PULSAR Festival 2023.',
      es: '<b>Symetric Live</b>, São Paulo, Brasil. Live act que combina precisión de producción con energía de pista. En Padang Records: remix <b>Alchemy Circle - RJ 2.0</b> y <b>Digital Forest</b> con Soulid (VA Padang × Noctusense). Live en PULSAR Festival 2023.',
      de: '<b>Symetric Live</b>, São Paulo, Brasilien. Live-Act, der Produktionspräzision mit Dancefloor-Energie verbindet. Auf Padang Records: Remix <b>Alchemy Circle - RJ 2.0</b> und <b>Digital Forest</b> mit Soulid (VA Padang × Noctusense). Live beim PULSAR Festival 2023.',
      fr: '<b>Symetric Live</b>, São Paulo, Brésil. Live act combinant précision de production et énergie de dancefloor. Sur Padang Records : remix <b>Alchemy Circle - RJ 2.0</b> et <b>Digital Forest</b> avec Soulid (VA Padang × Noctusense). Live au PULSAR Festival 2023.',
      ja: '<b>Symetric Live</b>、ブラジル・サンパウロ。プロダクションの精度とダンスフロアのエネルギーを融合させるライブアクト。Padang Records から：<b>Alchemy Circle - RJ 2.0</b> リミックスと、Soulid との <b>Digital Forest</b>（VA Padang × Noctusense）。PULSAR Festival 2023 でライブ。'
    },

    "Tekmall": {
      en: '<b>Vagner Donada</b>, Porto Alegre. Project founded in 2012 in southern Brazil. Deep Progressive Trance with a dark psychedelic touch — eccentric basslines, unique musicality, hypnotic atmosphere. Mixes his influences with the sci-fi genre. <b>On Padang Records:</b> compiled and curated <b>VA Reborn: Echoes of the Forest</b> (25/11/2025) — dedicated to the memory of his brother Leandro Donada. <b>Festivals:</b> <b>Earthdance Festival 2025</b>, <b>Undervision Festival 2021</b>, <b>Arkana Festival 2025</b> (Sacred Valley of the Incas, Peru), Padang Records × Blacklite.',
      es: '<b>Vagner Donada</b>, Porto Alegre. Proyecto fundado en 2012 en el sur de Brasil. Deep Progressive Trance con toque dark psicodélico — basslines excéntricos, musicalidad única, atmósfera hipnótica. Mezcla sus influencias con el género sci-fi. <b>En Padang Records:</b> compiló y curó <b>VA Reborn: Echoes of the Forest</b> (25/11/2025) — dedicado a la memoria de su hermano Leandro Donada. <b>Festivales:</b> <b>Earthdance Festival 2025</b>, <b>Undervision Festival 2021</b>, <b>Arkana Festival 2025</b> (Valle Sagrado de los Incas, Perú), Padang Records × Blacklite.',
      de: '<b>Vagner Donada</b>, Porto Alegre. Projekt 2012 in Südbrasilien gegründet. Deep Progressive Trance mit dunklem psychedelischem Touch — exzentrische Basslines, einzigartige Musikalität, hypnotische Atmosphäre. Mischt seine Einflüsse mit dem Sci-Fi-Genre. <b>Auf Padang Records:</b> kuratierte <b>VA Reborn: Echoes of the Forest</b> (25.11.2025) — gewidmet dem Andenken seines Bruders Leandro Donada. <b>Festivals:</b> <b>Earthdance Festival 2025</b>, <b>Undervision Festival 2021</b>, <b>Arkana Festival 2025</b> (Heiliges Tal der Inka, Peru), Padang Records × Blacklite.',
      fr: '<b>Vagner Donada</b>, Porto Alegre. Projet fondé en 2012 dans le sud du Brésil. Deep Progressive Trance avec une touche dark psychédélique — basslines excentriques, musicalité unique, atmosphère hypnotique. Mélange ses influences au genre sci-fi. <b>Sur Padang Records :</b> a compilé et curaté <b>VA Reborn: Echoes of the Forest</b> (25/11/2025) — dédié à la mémoire de son frère Leandro Donada. <b>Festivals :</b> <b>Earthdance Festival 2025</b>, <b>Undervision Festival 2021</b>, <b>Arkana Festival 2025</b> (Vallée Sacrée des Incas, Pérou), Padang Records × Blacklite.',
      ja: '<b>Vagner Donada</b>、ポルト・アレグレ。2012年にブラジル南部で始まったプロジェクト。ダーク・サイケデリックなタッチを持つ Deep Progressive Trance — エクセントリックなベースライン、独自のミュージカリティ、催眠的なアトモスフィア。SF ジャンルに影響を融合。<b>Padang Records から：</b><b>VA Reborn: Echoes of the Forest</b>（2025年11月25日）をキュレーション — 弟 Leandro Donada の追悼に捧げる。<b>フェス：</b><b>Earthdance Festival 2025</b>、<b>Undervision Festival 2021</b>、<b>Arkana Festival 2025</b>（インカ聖なる谷、ペルー）、Padang Records × Blacklite。'
    },

    "Tenebra": {
      en: '<b>Britt Rodrigues</b>, DJ/producer from Porto Alegre. Psytech and dark progressive — featured in the set <b>Tekmall b2b Tenebra @ Padang Records × Blacklite</b> (03/2026).',
      es: '<b>Britt Rodrigues</b>, DJ/productora de Porto Alegre. Psytech y dark progressive — apareció en el set <b>Tekmall b2b Tenebra @ Padang Records × Blacklite</b> (03/2026).',
      de: '<b>Britt Rodrigues</b>, DJ/Produzentin aus Porto Alegre. Psytech und Dark Progressive — zu hören im Set <b>Tekmall b2b Tenebra @ Padang Records × Blacklite</b> (03/2026).',
      fr: '<b>Britt Rodrigues</b>, DJ/productrice de Porto Alegre. Psytech et dark progressive — apparue dans le set <b>Tekmall b2b Tenebra @ Padang Records × Blacklite</b> (03/2026).',
      ja: '<b>Britt Rodrigues</b>、ブラジル・ポルト・アレグレ出身の DJ／プロデューサー。Psytech と Dark Progressive — <b>Tekmall b2b Tenebra @ Padang Records × Blacklite</b>（2026年3月）のセットに登場。'
    },

    "Tystix": {
      en: '<b>Tyler Archer</b>, originally from Garden Route, South Africa · now in Antwerp, Belgium. Producer focused on evolving psychedelic sound — futuristic sound design, nocturnal atmospheres, deep textures. <b>Dark progressive</b>. On Padang Records: <b>Signals EP</b> (02/2026). Side projects: Ocular Scope, Trogon, Gnosis. Sets at Origin (ZA), Modem Teaser Brussels, Vortex and Bucht der Träumer 2025.',
      es: '<b>Tyler Archer</b>, originalmente de Garden Route, Sudáfrica · ahora en Amberes, Bélgica. Productor centrado en sonido psicodélico en evolución — sound design futurista, atmósferas nocturnas, texturas profundas. <b>Dark progressive</b>. En Padang Records: <b>Signals EP</b> (02/2026). Side projects: Ocular Scope, Trogon, Gnosis. Sets en Origin (ZA), Modem Teaser Brussels, Vortex y Bucht der Träumer 2025.',
      de: '<b>Tyler Archer</b>, ursprünglich aus Garden Route, Südafrika · jetzt in Antwerpen, Belgien. Produzent, der sich auf einen sich wandelnden psychedelischen Sound konzentriert — futuristisches Sound-Design, nächtliche Atmosphären, tiefe Texturen. <b>Dark progressive</b>. Auf Padang Records: <b>Signals EP</b> (02/2026). Side-Projects: Ocular Scope, Trogon, Gnosis. Sets bei Origin (ZA), Modem Teaser Brussels, Vortex und Bucht der Träumer 2025.',
      fr: '<b>Tyler Archer</b>, originaire de Garden Route, Afrique du Sud · désormais à Anvers, Belgique. Producteur tourné vers un son psychédélique en évolution — sound design futuriste, atmosphères nocturnes, textures profondes. <b>Dark progressive</b>. Sur Padang Records : <b>Signals EP</b> (02/2026). Side projects : Ocular Scope, Trogon, Gnosis. Sets à Origin (ZA), Modem Teaser Brussels, Vortex et Bucht der Träumer 2025.',
      ja: '<b>Tyler Archer</b>、南アフリカ・ガーデンルート出身 · 現在ベルギー・アントワープ拠点。進化するサイケデリックサウンドに焦点を当てるプロデューサー — フューチャリスティックなサウンド・デザイン、夜のアトモスフィア、深いテクスチャ。<b>Dark progressive</b>。Padang Records から：<b>Signals EP</b>（2026年2月）。サイドプロジェクト：Ocular Scope、Trogon、Gnosis。Origin（ZA）、Modem Teaser Brussels、Vortex、Bucht der Träumer 2025 でセット。'
    },

    "Vorg": {
      en: '<b>Robson Morche</b>, Brazil. <b>Resident artist of Padang Records</b>. Psytrance, Dark Progressive and Zenonesque. "Project created and experimented by Robson Morche, building his own mental reconstruction over the years." <b>On Padang Records:</b> <b>QUBE EP</b> with Paracozm (2023), <b>Echoes EP</b> (2022), <b>Cyber Soul: Day</b> and <b>Cyber Soul: Night</b> (2025), track <b>Undercity</b> on Nyctophilia II (2026), Paracozm — Framed remix, Dienstmann vs Vorg — Fractal Dimensions. <b>Festivals:</b> Earthdance (Padang Lab Series EP.18), Ecotribe Festival, Merry XMAS Padang 2017.',
      es: '<b>Robson Morche</b>, Brasil. <b>Artista residente de Padang Records</b>. Psytrance, Dark Progressive y Zenonesque. "Proyecto creado y experimentado por Robson Morche, construyendo su propia reconstrucción mental a lo largo de los años." <b>En Padang Records:</b> <b>QUBE EP</b> con Paracozm (2023), <b>Echoes EP</b> (2022), <b>Cyber Soul: Day</b> y <b>Cyber Soul: Night</b> (2025), track <b>Undercity</b> en Nyctophilia II (2026), remix Paracozm — Framed, Dienstmann vs Vorg — Fractal Dimensions. <b>Festivales:</b> Earthdance (Padang Lab Series EP.18), Ecotribe Festival, Merry XMAS Padang 2017.',
      de: '<b>Robson Morche</b>, Brasilien. <b>Resident-Artist von Padang Records</b>. Psytrance, Dark Progressive und Zenonesque. "Projekt von Robson Morche kreiert und erprobt, der über die Jahre seine eigene mentale Rekonstruktion baut." <b>Auf Padang Records:</b> <b>QUBE EP</b> mit Paracozm (2023), <b>Echoes EP</b> (2022), <b>Cyber Soul: Day</b> und <b>Cyber Soul: Night</b> (2025), Track <b>Undercity</b> auf Nyctophilia II (2026), Paracozm — Framed Remix, Dienstmann vs Vorg — Fractal Dimensions. <b>Festivals:</b> Earthdance (Padang Lab Series EP.18), Ecotribe Festival, Merry XMAS Padang 2017.',
      fr: '<b>Robson Morche</b>, Brésil. <b>Artiste résident de Padang Records</b>. Psytrance, Dark Progressive et Zenonesque. « Projet créé et expérimenté par Robson Morche, construisant sa propre reconstruction mentale au fil des années. » <b>Sur Padang Records :</b> <b>QUBE EP</b> avec Paracozm (2023), <b>Echoes EP</b> (2022), <b>Cyber Soul: Day</b> et <b>Cyber Soul: Night</b> (2025), morceau <b>Undercity</b> sur Nyctophilia II (2026), remix Paracozm — Framed, Dienstmann vs Vorg — Fractal Dimensions. <b>Festivals :</b> Earthdance (Padang Lab Series EP.18), Ecotribe Festival, Merry XMAS Padang 2017.',
      ja: '<b>Robson Morche</b>、ブラジル。<b>Padang Records レジデント・アーティスト</b>。Psytrance、Dark Progressive、Zenonesque。「Robson Morche によって創られ実験されたプロジェクトで、長年にわたり自身のメンタルな再構築を組み立てている」。<b>Padang Records から：</b>Paracozm との <b>QUBE EP</b>（2023）、<b>Echoes EP</b>（2022）、<b>Cyber Soul: Day</b> と <b>Cyber Soul: Night</b>（2025）、Nyctophilia II の <b>Undercity</b>（2026）、Paracozm — Framed リミックス、Dienstmann vs Vorg — Fractal Dimensions。<b>フェス：</b>Earthdance（Padang Lab Series EP.18）、Ecotribe Festival、Merry XMAS Padang 2017。'
    },

    "Yazata": {
      en: '<b>YAZATA</b>. "Born with rhythm in her soul" — her journey began on the dance floor as a passionate dancer and lifelong music lover. In 2024 she stepped behind the decks to craft her own sonic journeys: a unique blend of haunting melodies, deep basslines and immersive atmospheres. Part of Padang Records — delivered <b>Padang Lab Series EP.14</b> (New Year Mix, 12/2024) and <b>YAYSG</b> Album Mix compiled by Stix.',
      es: '<b>YAZATA</b>. "Born with rhythm in her soul" — su viaje comenzó en la pista como bailarina apasionada y amante de la música. En 2024 dio el paso detrás de los decks para crear sus propios viajes sónicos: blend único de melodías inquietantes, basslines profundos y atmósferas inmersivas. Integra Padang Records — presentó <b>Padang Lab Series EP.14</b> (New Year Mix, 12/2024) y <b>YAYSG</b> Album Mix compilado por Stix.',
      de: '<b>YAZATA</b>. "Born with rhythm in her soul" — ihre Reise begann auf der Tanzfläche als leidenschaftliche Tänzerin und lebenslange Musikliebhaberin. 2024 trat sie hinter die Decks, um ihre eigenen klanglichen Reisen zu gestalten: eine einzigartige Mischung aus haunting Melodien, tiefen Basslines und immersiven Atmosphären. Teil von Padang Records — lieferte <b>Padang Lab Series EP.14</b> (New Year Mix, 12/2024) und <b>YAYSG</b> Album Mix, kuratiert von Stix.',
      fr: '<b>YAZATA</b>. « Born with rhythm in her soul » — son voyage a commencé sur la piste, danseuse passionnée et amoureuse de la musique. En 2024 elle est passée derrière les platines pour façonner ses propres voyages sonores : un mélange unique de mélodies hantées, de basslines profondes et d\'atmosphères immersives. Intègre Padang Records — a livré <b>Padang Lab Series EP.14</b> (New Year Mix, 12/2024) et <b>YAYSG</b> Album Mix compilé par Stix.',
      ja: '<b>YAZATA</b>。「Born with rhythm in her soul」 — 彼女の旅は、情熱的なダンサーであり生涯の音楽愛好家として、ダンスフロアから始まった。2024年にデッキの後ろに立ち、自身の音の旅を紡ぎ始める：哀愁あるメロディ、深いベースライン、没入感のあるアトモスフィアのユニークなブレンド。Padang Records の一員 — <b>Padang Lab Series EP.14</b>（New Year Mix、2024年12月）を担当し、Stix がコンパイルした <b>YAYSG</b> Album Mix にも参加。'
    }
  };

  // ── Hook MutationObserver na modal de roster.html ──
  // Quando .modal recebe class "show", traduz a bio conforme idioma ativo.
  function currentLang() {
    return document.documentElement.lang || 'pt';
  }

  function translateModalBio() {
    const lang = currentLang();
    if (lang === 'pt') return; // PT é source — fica como está
    const nm = document.getElementById('mNm');
    const bio = document.getElementById('mBio');
    if (!nm || !bio) return;
    const artist = (nm.textContent || '').trim();
    const entry = BIOS[artist];
    if (entry && entry[lang]) {
      bio.innerHTML = entry[lang];
    }
  }

  function attach() {
    const modal = document.getElementById('modal');
    if (!modal) { return setTimeout(attach, 100); }
    const obs = new MutationObserver(muts => {
      for (const m of muts) {
        if (m.attributeName === 'class' && modal.classList.contains('show')) {
          // pequeno delay pra garantir que openArtist() já setou mNm e mBio
          setTimeout(translateModalBio, 30);
        }
      }
    });
    obs.observe(modal, { attributes: true, attributeFilter: ['class'] });

    // também re-traduz quando o usuário troca de idioma com a modal aberta
    document.querySelectorAll('.lang-switch button').forEach(btn => {
      btn.addEventListener('click', () => {
        if (modal.classList.contains('show')) {
          setTimeout(translateModalBio, 30);
        }
      });
    });
  }

  // expõe pra eventual uso externo
  window.PADANG_BIOS = BIOS;

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', attach);
  } else {
    attach();
  }
})();
